servers:
  - name: weather
    cmd:
      [
        "/bin/sh",
        "-c",
        "node ./weather-demo-mcp/build/index.js",
      ]
    idleSeconds: 60
    maxConcurrent: 1
    sticky: false
    persistent: false
    minReady: 1
    protocolVersion: "2025-11-25"