version: '3'

includes:
  common: ./build/Taskfile.yml
  # windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  # linux: ./build/linux/Taskfile.yml

vars:
  APP_NAME: "mcpdui"
  CLI_NAME: "mcpdmcp"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 5173}}'
  WAILS: '{{.WAILS | default (printf "%s/bin/wails3" .ROOT_DIR)}}'
  # Version configuration - synced with Makefile
  VERSION: '{{.VERSION | default "dev"}}'
  BUILD:
    sh: git log -n 1 --format=%h

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"
        vars:
          VERSION: "{{.VERSION}}"
          BUILD: "{{.BUILD}}"

  package:
    summary: Packages a production build of the application
    cmds:
      - task: "{{OS}}:package"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - '{{.WAILS}} dev -config ./build/config.yml -port {{.VITE_PORT}}'

  setup:docker:
    summary: Builds Docker image for cross-compilation (~800MB download)
    cmds:
      - task: common:setup:docker
