// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService exposes configuration management APIs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfigMode returns configuration mode metadata.
 */
export function GetConfigMode(): $CancellablePromise<$models.ConfigModeResponse> {
    return $Call.ByID(4132860316).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetConfigPath returns configuration path.
 */
export function GetConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(289727796);
}

/**
 * GetRuntimeConfig loads runtime configuration from the config file.
 */
export function GetRuntimeConfig(): $CancellablePromise<$models.RuntimeConfigDetail> {
    return $Call.ByID(3607584597).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ImportMcpServers writes imported MCP servers into the config file.
 */
export function ImportMcpServers(req: $models.ImportMcpServersRequest): $CancellablePromise<void> {
    return $Call.ByID(3537283842, req);
}

/**
 * OpenConfigInEditor opens config path in system editor.
 */
export function OpenConfigInEditor(): $CancellablePromise<void> {
    return $Call.ByID(2218954059);
}

/**
 * ReloadConfig triggers a configuration reload in the running Core.
 */
export function ReloadConfig(): $CancellablePromise<void> {
    return $Call.ByID(3451945896);
}

/**
 * UpdateRuntimeConfig writes runtime updates into the config file.
 */
export function UpdateRuntimeConfig(req: $models.UpdateRuntimeConfigRequest): $CancellablePromise<void> {
    return $Call.ByID(2487410792, req);
}

// Private type creation functions
const $$createType0 = $models.ConfigModeResponse.createFrom;
const $$createType1 = $models.RuntimeConfigDetail.createFrom;
