// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiscoveryService exposes tools/resources/prompts APIs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CallTool calls a tool.
 */
export function CallTool(name: string, args: json$0.RawMessage, routingKey: string): $CancellablePromise<json$0.RawMessage> {
    return $Call.ByID(216212321, name, args, routingKey);
}

/**
 * GetPrompt gets a prompt template.
 */
export function GetPrompt(name: string, args: json$0.RawMessage): $CancellablePromise<json$0.RawMessage> {
    return $Call.ByID(260479231, name, args);
}

/**
 * ListPrompts lists prompt templates.
 */
export function ListPrompts(cursor: string): $CancellablePromise<$models.PromptPage | null> {
    return $Call.ByID(1816633378, cursor).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListResources lists resources.
 */
export function ListResources(cursor: string): $CancellablePromise<$models.ResourcePage | null> {
    return $Call.ByID(1140104168, cursor).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListTools lists all available tools.
 */
export function ListTools(): $CancellablePromise<$models.ToolEntry[]> {
    return $Call.ByID(3993039598).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ReadResource reads resource content.
 */
export function ReadResource(uri: string): $CancellablePromise<json$0.RawMessage> {
    return $Call.ByID(2031160199, uri);
}

// Private type creation functions
const $$createType0 = $models.PromptPage.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ResourcePage.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.ToolEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
