// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PluginService exposes plugin management APIs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetPluginList returns all configured plugins with their current state and metrics.
 */
export function GetPluginList(): $CancellablePromise<$models.PluginListEntry[]> {
    return $Call.ByID(3741487613).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetPluginMetrics returns aggregated metrics for all plugins.
 */
export function GetPluginMetrics(): $CancellablePromise<{ [_: string]: $models.PluginMetrics }> {
    return $Call.ByID(423050562).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * TogglePlugin enables or disables a plugin by triggering a config reload.
 */
export function TogglePlugin(req: $models.TogglePluginRequest): $CancellablePromise<void> {
    return $Call.ByID(90978349, req);
}

// Private type creation functions
const $$createType0 = $models.PluginListEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.PluginMetrics.createFrom;
const $$createType3 = $Create.Map($Create.Any, $$createType2);
