// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
)

// Injectors from wire.go:

func InitializeApplication(ctx context.Context, cfg ServeConfig, logging LoggingConfig) (*Application, error) {
	appLogging := NewLogging(logging)
	logger := NewLogger(appLogging)
	registry := NewMetricsRegistry()
	metrics := NewMetrics(registry)
	healthTracker := NewHealthTracker()
	dynamicCatalogProvider, err := NewDynamicCatalogProvider(ctx, cfg, logger)
	if err != nil {
		return nil, err
	}
	catalogState, err := NewCatalogState(ctx, dynamicCatalogProvider)
	if err != nil {
		return nil, err
	}
	launcher := NewCommandLauncher(logger)
	listChangeHub := NewListChangeHub()
	transport := NewMCPTransport(logger, listChangeHub)
	lifecycle := NewLifecycleManager(ctx, launcher, transport, logger)
	pingProbe := NewPingProbe()
	scheduler, err := NewScheduler(lifecycle, catalogState, pingProbe, metrics, healthTracker, logger)
	if err != nil {
		return nil, err
	}
	v := NewProfileRuntimes(catalogState, scheduler, metrics, healthTracker, listChangeHub, logger)
	serverInitializationManager := NewServerInitializationManager(scheduler, catalogState, logger)
	appControlPlaneState := NewControlPlaneState(ctx, v, catalogState, scheduler, serverInitializationManager, logger)
	appCallerRegistry := newCallerRegistry(appControlPlaneState)
	appDiscoveryService := newDiscoveryService(appControlPlaneState, appCallerRegistry)
	logBroadcaster := NewLogBroadcaster(appLogging)
	appObservabilityService := newObservabilityService(appControlPlaneState, appCallerRegistry, logBroadcaster)
	appAutomationService := newAutomationService(appControlPlaneState, appCallerRegistry, appDiscoveryService)
	controlPlane := NewControlPlane(appControlPlaneState, appCallerRegistry, appDiscoveryService, appObservabilityService, appAutomationService)
	server := NewRPCServer(controlPlane, catalogState, logger)
	reloadManager := NewReloadManager(dynamicCatalogProvider, appControlPlaneState, appCallerRegistry, scheduler, serverInitializationManager, metrics, healthTracker, listChangeHub, logger)
	application := NewApplication(ctx, cfg, logger, registry, metrics, healthTracker, catalogState, appControlPlaneState, scheduler, serverInitializationManager, controlPlane, server, reloadManager)
	return application, nil
}
