// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService exposes configuration management APIs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfigMode returns configuration mode metadata.
 */
export function GetConfigMode(): $CancellablePromise<$models.ConfigModeResponse> {
    return $Call.ByID(2281598782).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetConfigPath returns configuration path.
 */
export function GetConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(430178106);
}

/**
 * ImportMcpServers writes imported MCP servers into selected profiles.
 */
export function ImportMcpServers(req: $models.ImportMcpServersRequest): $CancellablePromise<void> {
    return $Call.ByID(1112164916, req);
}

/**
 * OpenConfigInEditor opens config path in system editor.
 */
export function OpenConfigInEditor(): $CancellablePromise<void> {
    return $Call.ByID(3550689645);
}

/**
 * ReloadConfig triggers a configuration reload in the running Core.
 */
export function ReloadConfig(): $CancellablePromise<void> {
    return $Call.ByID(3781415734);
}

/**
 * UpdateRuntimeConfig writes runtime.yaml updates to the profile store.
 */
export function UpdateRuntimeConfig(req: $models.UpdateRuntimeConfigRequest): $CancellablePromise<void> {
    return $Call.ByID(3819242306, req);
}

// Private type creation functions
const $$createType0 = $models.ConfigModeResponse.createFrom;
