// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CoreService exposes core lifecycle APIs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetBootstrapProgress returns bootstrap progress.
 */
export function GetBootstrapProgress(): $CancellablePromise<$models.BootstrapProgressResponse> {
    return $Call.ByID(2470627769).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetCoreState returns current core state.
 */
export function GetCoreState(): $CancellablePromise<$models.CoreStateResponse> {
    return $Call.ByID(620198224).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetInfo returns control plane info.
 */
export function GetInfo(): $CancellablePromise<$models.InfoResponse> {
    return $Call.ByID(3148170924).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * RestartCore restarts the core.
 */
export function RestartCore(): $CancellablePromise<void> {
    return $Call.ByID(2631306004);
}

/**
 * StartCore starts the core.
 */
export function StartCore(): $CancellablePromise<void> {
    return $Call.ByID(262848791);
}

/**
 * StartCoreWithOptions starts the core with explicit options.
 */
export function StartCoreWithOptions(opts: $models.StartCoreOptions): $CancellablePromise<void> {
    return $Call.ByID(447675163, opts);
}

/**
 * StopCore stops the core.
 */
export function StopCore(): $CancellablePromise<void> {
    return $Call.ByID(3055852507);
}

// Private type creation functions
const $$createType0 = $models.BootstrapProgressResponse.createFrom;
const $$createType1 = $models.CoreStateResponse.createFrom;
const $$createType2 = $models.InfoResponse.createFrom;
