// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as WailsService from "./wailsservice.js";
export {
    WailsService
};

export {
    CoreStateResponse,
    InfoResponse,
    Manager,
    PromptEntry,
    PromptPage,
    ResourceEntry,
    ResourcePage,
    ToolEntry
} from "./models.js";
