// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

export class ActiveCaller {
    "caller": string;
    "pid": number;
    "profile": string;
    "lastHeartbeat": string;

    /** Creates a new ActiveCaller instance. */
    constructor($$source: Partial<ActiveCaller> = {}) {
        if (!("caller" in $$source)) {
            this["caller"] = "";
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("profile" in $$source)) {
            this["profile"] = "";
        }
        if (!("lastHeartbeat" in $$source)) {
            this["lastHeartbeat"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActiveCaller instance from a string or object.
     */
    static createFrom($$source: any = {}): ActiveCaller {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActiveCaller($$parsedSource as Partial<ActiveCaller>);
    }
}

/**
 * BootstrapProgressResponse represents bootstrap progress for the frontend.
 */
export class BootstrapProgressResponse {
    "state": string;
    "total": number;
    "completed": number;
    "failed": number;
    "current": string;
    "errors"?: { [_: string]: string };

    /** Creates a new BootstrapProgressResponse instance. */
    constructor($$source: Partial<BootstrapProgressResponse> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("completed" in $$source)) {
            this["completed"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("current" in $$source)) {
            this["current"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BootstrapProgressResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): BootstrapProgressResponse {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField5_0($$parsedSource["errors"]);
        }
        return new BootstrapProgressResponse($$parsedSource as Partial<BootstrapProgressResponse>);
    }
}

/**
 * ConfigModeResponse indicates the configuration mode and path
 */
export class ConfigModeResponse {
    /**
     * "directory" or "unknown"
     */
    "mode": string;

    /**
     * Configuration path
     */
    "path": string;

    /**
     * Whether the config is writable
     */
    "isWritable": boolean;

    /** Creates a new ConfigModeResponse instance. */
    constructor($$source: Partial<ConfigModeResponse> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isWritable" in $$source)) {
            this["isWritable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigModeResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigModeResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigModeResponse($$parsedSource as Partial<ConfigModeResponse>);
    }
}

/**
 * CoreStateResponse is the core lifecycle status for the frontend.
 */
export class CoreStateResponse {
    "state": string;
    "uptime": number;
    "error"?: string;

    /** Creates a new CoreStateResponse instance. */
    constructor($$source: Partial<CoreStateResponse> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("uptime" in $$source)) {
            this["uptime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoreStateResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): CoreStateResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CoreStateResponse($$parsedSource as Partial<CoreStateResponse>);
    }
}

/**
 * CreateProfileRequest creates a new profile file.
 */
export class CreateProfileRequest {
    "name": string;

    /** Creates a new CreateProfileRequest instance. */
    constructor($$source: Partial<CreateProfileRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateProfileRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateProfileRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateProfileRequest($$parsedSource as Partial<CreateProfileRequest>);
    }
}

/**
 * DebugSnapshotResponse is the metadata returned after exporting a debug snapshot.
 */
export class DebugSnapshotResponse {
    "path": string;
    "size": number;
    "generatedAt": string;

    /** Creates a new DebugSnapshotResponse instance. */
    constructor($$source: Partial<DebugSnapshotResponse> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("generatedAt" in $$source)) {
            this["generatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DebugSnapshotResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): DebugSnapshotResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DebugSnapshotResponse($$parsedSource as Partial<DebugSnapshotResponse>);
    }
}

/**
 * DeleteProfileRequest removes a profile file.
 */
export class DeleteProfileRequest {
    "name": string;

    /** Creates a new DeleteProfileRequest instance. */
    constructor($$source: Partial<DeleteProfileRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteProfileRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteProfileRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteProfileRequest($$parsedSource as Partial<DeleteProfileRequest>);
    }
}

/**
 * DeleteServerRequest removes a server from a profile.
 */
export class DeleteServerRequest {
    "profile": string;
    "server": string;

    /** Creates a new DeleteServerRequest instance. */
    constructor($$source: Partial<DeleteServerRequest> = {}) {
        if (!("profile" in $$source)) {
            this["profile"] = "";
        }
        if (!("server" in $$source)) {
            this["server"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteServerRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteServerRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteServerRequest($$parsedSource as Partial<DeleteServerRequest>);
    }
}

/**
 * ImportMcpServersRequest is the payload for importing MCP servers into profiles.
 */
export class ImportMcpServersRequest {
    "profiles": string[];
    "servers": ImportServerSpec[];

    /** Creates a new ImportMcpServersRequest instance. */
    constructor($$source: Partial<ImportMcpServersRequest> = {}) {
        if (!("profiles" in $$source)) {
            this["profiles"] = [];
        }
        if (!("servers" in $$source)) {
            this["servers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportMcpServersRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportMcpServersRequest {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField0_0($$parsedSource["profiles"]);
        }
        if ("servers" in $$parsedSource) {
            $$parsedSource["servers"] = $$createField1_0($$parsedSource["servers"]);
        }
        return new ImportMcpServersRequest($$parsedSource as Partial<ImportMcpServersRequest>);
    }
}

/**
 * ImportServerSpec represents a server spec from MCP JSON import.
 */
export class ImportServerSpec {
    "name": string;
    "cmd": string[];
    "env"?: { [_: string]: string };
    "cwd"?: string;

    /** Creates a new ImportServerSpec instance. */
    constructor($$source: Partial<ImportServerSpec> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("cmd" in $$source)) {
            this["cmd"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportServerSpec instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportServerSpec {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cmd" in $$parsedSource) {
            $$parsedSource["cmd"] = $$createField1_0($$parsedSource["cmd"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField2_0($$parsedSource["env"]);
        }
        return new ImportServerSpec($$parsedSource as Partial<ImportServerSpec>);
    }
}

/**
 * InfoResponse exposes control plane metadata to the frontend.
 */
export class InfoResponse {
    "name": string;
    "version": string;
    "build": string;

    /** Creates a new InfoResponse instance. */
    constructor($$source: Partial<InfoResponse> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("build" in $$source)) {
            this["build"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InfoResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): InfoResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InfoResponse($$parsedSource as Partial<InfoResponse>);
    }
}

/**
 * InstanceStatus represents the status of a single server instance
 */
export class InstanceStatus {
    "id": string;
    "state": string;
    "busyCount": number;
    "lastActive": string;
    "spawnedAt": string;
    "handshakedAt": string;
    "lastHeartbeatAt": string;
    "lastStartCause"?: StartCause | null;

    /** Creates a new InstanceStatus instance. */
    constructor($$source: Partial<InstanceStatus> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("busyCount" in $$source)) {
            this["busyCount"] = 0;
        }
        if (!("lastActive" in $$source)) {
            this["lastActive"] = "";
        }
        if (!("spawnedAt" in $$source)) {
            this["spawnedAt"] = "";
        }
        if (!("handshakedAt" in $$source)) {
            this["handshakedAt"] = "";
        }
        if (!("lastHeartbeatAt" in $$source)) {
            this["lastHeartbeatAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstanceStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): InstanceStatus {
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lastStartCause" in $$parsedSource) {
            $$parsedSource["lastStartCause"] = $$createField7_0($$parsedSource["lastStartCause"]);
        }
        return new InstanceStatus($$parsedSource as Partial<InstanceStatus>);
    }
}

/**
 * ObservabilityConfigDetail for frontend
 */
export class ObservabilityConfigDetail {
    "listenAddress": string;

    /** Creates a new ObservabilityConfigDetail instance. */
    constructor($$source: Partial<ObservabilityConfigDetail> = {}) {
        if (!("listenAddress" in $$source)) {
            this["listenAddress"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ObservabilityConfigDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): ObservabilityConfigDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ObservabilityConfigDetail($$parsedSource as Partial<ObservabilityConfigDetail>);
    }
}

export class PoolMetrics {
    "startCount": number;
    "stopCount": number;
    "totalCalls": number;
    "totalErrors": number;
    "totalDurationMs": number;
    "lastCallAt": string;

    /** Creates a new PoolMetrics instance. */
    constructor($$source: Partial<PoolMetrics> = {}) {
        if (!("startCount" in $$source)) {
            this["startCount"] = 0;
        }
        if (!("stopCount" in $$source)) {
            this["stopCount"] = 0;
        }
        if (!("totalCalls" in $$source)) {
            this["totalCalls"] = 0;
        }
        if (!("totalErrors" in $$source)) {
            this["totalErrors"] = 0;
        }
        if (!("totalDurationMs" in $$source)) {
            this["totalDurationMs"] = 0;
        }
        if (!("lastCallAt" in $$source)) {
            this["lastCallAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PoolMetrics instance from a string or object.
     */
    static createFrom($$source: any = {}): PoolMetrics {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PoolMetrics($$parsedSource as Partial<PoolMetrics>);
    }
}

/**
 * PoolStats contains aggregated statistics for a server pool
 */
export class PoolStats {
    "total": number;
    "ready": number;
    "busy": number;
    "starting": number;
    "initializing": number;
    "handshaking": number;
    "draining": number;
    "failed": number;

    /** Creates a new PoolStats instance. */
    constructor($$source: Partial<PoolStats> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("ready" in $$source)) {
            this["ready"] = 0;
        }
        if (!("busy" in $$source)) {
            this["busy"] = 0;
        }
        if (!("starting" in $$source)) {
            this["starting"] = 0;
        }
        if (!("initializing" in $$source)) {
            this["initializing"] = 0;
        }
        if (!("handshaking" in $$source)) {
            this["handshaking"] = 0;
        }
        if (!("draining" in $$source)) {
            this["draining"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PoolStats instance from a string or object.
     */
    static createFrom($$source: any = {}): PoolStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PoolStats($$parsedSource as Partial<PoolStats>);
    }
}

/**
 * ProfileDetail contains full profile configuration
 */
export class ProfileDetail {
    "name": string;
    "runtime": RuntimeConfigDetail;
    "servers": ServerSpecDetail[];
    "subAgent": ProfileSubAgentConfigDetail;

    /** Creates a new ProfileDetail instance. */
    constructor($$source: Partial<ProfileDetail> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("runtime" in $$source)) {
            this["runtime"] = (new RuntimeConfigDetail());
        }
        if (!("servers" in $$source)) {
            this["servers"] = [];
        }
        if (!("subAgent" in $$source)) {
            this["subAgent"] = (new ProfileSubAgentConfigDetail());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileDetail {
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType8;
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("runtime" in $$parsedSource) {
            $$parsedSource["runtime"] = $$createField1_0($$parsedSource["runtime"]);
        }
        if ("servers" in $$parsedSource) {
            $$parsedSource["servers"] = $$createField2_0($$parsedSource["servers"]);
        }
        if ("subAgent" in $$parsedSource) {
            $$parsedSource["subAgent"] = $$createField3_0($$parsedSource["subAgent"]);
        }
        return new ProfileDetail($$parsedSource as Partial<ProfileDetail>);
    }
}

/**
 * ProfileSubAgentConfigDetail contains the per-profile SubAgent settings
 */
export class ProfileSubAgentConfigDetail {
    "enabled": boolean;

    /** Creates a new ProfileSubAgentConfigDetail instance. */
    constructor($$source: Partial<ProfileSubAgentConfigDetail> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileSubAgentConfigDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileSubAgentConfigDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileSubAgentConfigDetail($$parsedSource as Partial<ProfileSubAgentConfigDetail>);
    }
}

/**
 * ProfileSummary provides a brief overview of a profile
 */
export class ProfileSummary {
    "name": string;
    "serverCount": number;
    "isDefault": boolean;

    /** Creates a new ProfileSummary instance. */
    constructor($$source: Partial<ProfileSummary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("serverCount" in $$source)) {
            this["serverCount"] = 0;
        }
        if (!("isDefault" in $$source)) {
            this["isDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileSummary($$parsedSource as Partial<ProfileSummary>);
    }
}

/**
 * PromptEntry represents a single prompt for the frontend
 */
export class PromptEntry {
    "name": string;
    "promptJson": json$0.RawMessage;

    /** Creates a new PromptEntry instance. */
    constructor($$source: Partial<PromptEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("promptJson" in $$source)) {
            this["promptJson"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptEntry($$parsedSource as Partial<PromptEntry>);
    }
}

/**
 * PromptPage represents a paginated list of prompts
 */
export class PromptPage {
    "prompts": PromptEntry[];
    "nextCursor"?: string;

    /** Creates a new PromptPage instance. */
    constructor($$source: Partial<PromptPage> = {}) {
        if (!("prompts" in $$source)) {
            this["prompts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptPage instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptPage {
        const $$createField0_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("prompts" in $$parsedSource) {
            $$parsedSource["prompts"] = $$createField0_0($$parsedSource["prompts"]);
        }
        return new PromptPage($$parsedSource as Partial<PromptPage>);
    }
}

/**
 * RPCConfigDetail for frontend
 */
export class RPCConfigDetail {
    "listenAddress": string;
    "maxRecvMsgSize": number;
    "maxSendMsgSize": number;
    "keepaliveTimeSeconds": number;
    "keepaliveTimeoutSeconds": number;
    "socketMode": string;
    "tls": RPCTLSConfigDetail;

    /** Creates a new RPCConfigDetail instance. */
    constructor($$source: Partial<RPCConfigDetail> = {}) {
        if (!("listenAddress" in $$source)) {
            this["listenAddress"] = "";
        }
        if (!("maxRecvMsgSize" in $$source)) {
            this["maxRecvMsgSize"] = 0;
        }
        if (!("maxSendMsgSize" in $$source)) {
            this["maxSendMsgSize"] = 0;
        }
        if (!("keepaliveTimeSeconds" in $$source)) {
            this["keepaliveTimeSeconds"] = 0;
        }
        if (!("keepaliveTimeoutSeconds" in $$source)) {
            this["keepaliveTimeoutSeconds"] = 0;
        }
        if (!("socketMode" in $$source)) {
            this["socketMode"] = "";
        }
        if (!("tls" in $$source)) {
            this["tls"] = (new RPCTLSConfigDetail());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RPCConfigDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): RPCConfigDetail {
        const $$createField6_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tls" in $$parsedSource) {
            $$parsedSource["tls"] = $$createField6_0($$parsedSource["tls"]);
        }
        return new RPCConfigDetail($$parsedSource as Partial<RPCConfigDetail>);
    }
}

/**
 * RPCTLSConfigDetail for frontend
 */
export class RPCTLSConfigDetail {
    "enabled": boolean;
    "certFile": string;
    "keyFile": string;
    "caFile": string;
    "clientAuth": boolean;

    /** Creates a new RPCTLSConfigDetail instance. */
    constructor($$source: Partial<RPCTLSConfigDetail> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("certFile" in $$source)) {
            this["certFile"] = "";
        }
        if (!("keyFile" in $$source)) {
            this["keyFile"] = "";
        }
        if (!("caFile" in $$source)) {
            this["caFile"] = "";
        }
        if (!("clientAuth" in $$source)) {
            this["clientAuth"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RPCTLSConfigDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): RPCTLSConfigDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RPCTLSConfigDetail($$parsedSource as Partial<RPCTLSConfigDetail>);
    }
}

/**
 * ResourceEntry represents a single resource for the frontend
 */
export class ResourceEntry {
    "uri": string;
    "resourceJson": json$0.RawMessage;

    /** Creates a new ResourceEntry instance. */
    constructor($$source: Partial<ResourceEntry> = {}) {
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("resourceJson" in $$source)) {
            this["resourceJson"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceEntry($$parsedSource as Partial<ResourceEntry>);
    }
}

/**
 * ResourcePage represents a paginated list of resources
 */
export class ResourcePage {
    "resources": ResourceEntry[];
    "nextCursor"?: string;

    /** Creates a new ResourcePage instance. */
    constructor($$source: Partial<ResourcePage> = {}) {
        if (!("resources" in $$source)) {
            this["resources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourcePage instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourcePage {
        const $$createField0_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resources" in $$parsedSource) {
            $$parsedSource["resources"] = $$createField0_0($$parsedSource["resources"]);
        }
        return new ResourcePage($$parsedSource as Partial<ResourcePage>);
    }
}

export class RetryServerInitRequest {
    "specKey": string;

    /** Creates a new RetryServerInitRequest instance. */
    constructor($$source: Partial<RetryServerInitRequest> = {}) {
        if (!("specKey" in $$source)) {
            this["specKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RetryServerInitRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RetryServerInitRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RetryServerInitRequest($$parsedSource as Partial<RetryServerInitRequest>);
    }
}

/**
 * RuntimeConfigDetail contains runtime configuration for frontend
 */
export class RuntimeConfigDetail {
    "routeTimeoutSeconds": number;
    "pingIntervalSeconds": number;
    "toolRefreshSeconds": number;
    "toolRefreshConcurrency": number;
    "callerCheckSeconds": number;
    "callerInactiveSeconds": number;
    "serverInitRetryBaseSeconds": number;
    "serverInitRetryMaxSeconds": number;
    "serverInitMaxRetries": number;
    "bootstrapMode": string;
    "bootstrapConcurrency": number;
    "bootstrapTimeoutSeconds": number;
    "defaultActivationMode": string;
    "exposeTools": boolean;
    "toolNamespaceStrategy": string;
    "observability": ObservabilityConfigDetail;
    "rpc": RPCConfigDetail;

    /** Creates a new RuntimeConfigDetail instance. */
    constructor($$source: Partial<RuntimeConfigDetail> = {}) {
        if (!("routeTimeoutSeconds" in $$source)) {
            this["routeTimeoutSeconds"] = 0;
        }
        if (!("pingIntervalSeconds" in $$source)) {
            this["pingIntervalSeconds"] = 0;
        }
        if (!("toolRefreshSeconds" in $$source)) {
            this["toolRefreshSeconds"] = 0;
        }
        if (!("toolRefreshConcurrency" in $$source)) {
            this["toolRefreshConcurrency"] = 0;
        }
        if (!("callerCheckSeconds" in $$source)) {
            this["callerCheckSeconds"] = 0;
        }
        if (!("callerInactiveSeconds" in $$source)) {
            this["callerInactiveSeconds"] = 0;
        }
        if (!("serverInitRetryBaseSeconds" in $$source)) {
            this["serverInitRetryBaseSeconds"] = 0;
        }
        if (!("serverInitRetryMaxSeconds" in $$source)) {
            this["serverInitRetryMaxSeconds"] = 0;
        }
        if (!("serverInitMaxRetries" in $$source)) {
            this["serverInitMaxRetries"] = 0;
        }
        if (!("bootstrapMode" in $$source)) {
            this["bootstrapMode"] = "";
        }
        if (!("bootstrapConcurrency" in $$source)) {
            this["bootstrapConcurrency"] = 0;
        }
        if (!("bootstrapTimeoutSeconds" in $$source)) {
            this["bootstrapTimeoutSeconds"] = 0;
        }
        if (!("defaultActivationMode" in $$source)) {
            this["defaultActivationMode"] = "";
        }
        if (!("exposeTools" in $$source)) {
            this["exposeTools"] = false;
        }
        if (!("toolNamespaceStrategy" in $$source)) {
            this["toolNamespaceStrategy"] = "";
        }
        if (!("observability" in $$source)) {
            this["observability"] = (new ObservabilityConfigDetail());
        }
        if (!("rpc" in $$source)) {
            this["rpc"] = (new RPCConfigDetail());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeConfigDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): RuntimeConfigDetail {
        const $$createField15_0 = $$createType15;
        const $$createField16_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("observability" in $$parsedSource) {
            $$parsedSource["observability"] = $$createField15_0($$parsedSource["observability"]);
        }
        if ("rpc" in $$parsedSource) {
            $$parsedSource["rpc"] = $$createField16_0($$parsedSource["rpc"]);
        }
        return new RuntimeConfigDetail($$parsedSource as Partial<RuntimeConfigDetail>);
    }
}

export class ServerInitStatus {
    "specKey": string;
    "serverName": string;
    "minReady": number;
    "ready": number;
    "failed": number;
    "state": string;
    "lastError"?: string;
    "retryCount": number;
    "nextRetryAt"?: string;
    "updatedAt": string;

    /** Creates a new ServerInitStatus instance. */
    constructor($$source: Partial<ServerInitStatus> = {}) {
        if (!("specKey" in $$source)) {
            this["specKey"] = "";
        }
        if (!("serverName" in $$source)) {
            this["serverName"] = "";
        }
        if (!("minReady" in $$source)) {
            this["minReady"] = 0;
        }
        if (!("ready" in $$source)) {
            this["ready"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("retryCount" in $$source)) {
            this["retryCount"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerInitStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerInitStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerInitStatus($$parsedSource as Partial<ServerInitStatus>);
    }
}

/**
 * ServerRuntimeStatus contains the runtime status of a server and its instances
 */
export class ServerRuntimeStatus {
    "specKey": string;
    "serverName": string;
    "instances": InstanceStatus[];
    "stats": PoolStats;
    "metrics": PoolMetrics;

    /** Creates a new ServerRuntimeStatus instance. */
    constructor($$source: Partial<ServerRuntimeStatus> = {}) {
        if (!("specKey" in $$source)) {
            this["specKey"] = "";
        }
        if (!("serverName" in $$source)) {
            this["serverName"] = "";
        }
        if (!("instances" in $$source)) {
            this["instances"] = [];
        }
        if (!("stats" in $$source)) {
            this["stats"] = (new PoolStats());
        }
        if (!("metrics" in $$source)) {
            this["metrics"] = (new PoolMetrics());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerRuntimeStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerRuntimeStatus {
        const $$createField2_0 = $$createType18;
        const $$createField3_0 = $$createType19;
        const $$createField4_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("instances" in $$parsedSource) {
            $$parsedSource["instances"] = $$createField2_0($$parsedSource["instances"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField3_0($$parsedSource["stats"]);
        }
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField4_0($$parsedSource["metrics"]);
        }
        return new ServerRuntimeStatus($$parsedSource as Partial<ServerRuntimeStatus>);
    }
}

/**
 * ServerSpecDetail contains server specification for frontend
 */
export class ServerSpecDetail {
    "name": string;
    "specKey": string;
    "cmd": string[];
    "env": { [_: string]: string };
    "cwd": string;
    "idleSeconds": number;
    "maxConcurrent": number;
    "strategy": string;
    "sessionTTLSeconds": number;
    "disabled": boolean;
    "minReady": number;
    "activationMode": string;
    "drainTimeoutSeconds": number;
    "protocolVersion": string;
    "exposeTools": string[];

    /** Creates a new ServerSpecDetail instance. */
    constructor($$source: Partial<ServerSpecDetail> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("specKey" in $$source)) {
            this["specKey"] = "";
        }
        if (!("cmd" in $$source)) {
            this["cmd"] = [];
        }
        if (!("env" in $$source)) {
            this["env"] = {};
        }
        if (!("cwd" in $$source)) {
            this["cwd"] = "";
        }
        if (!("idleSeconds" in $$source)) {
            this["idleSeconds"] = 0;
        }
        if (!("maxConcurrent" in $$source)) {
            this["maxConcurrent"] = 0;
        }
        if (!("strategy" in $$source)) {
            this["strategy"] = "";
        }
        if (!("sessionTTLSeconds" in $$source)) {
            this["sessionTTLSeconds"] = 0;
        }
        if (!("disabled" in $$source)) {
            this["disabled"] = false;
        }
        if (!("minReady" in $$source)) {
            this["minReady"] = 0;
        }
        if (!("activationMode" in $$source)) {
            this["activationMode"] = "";
        }
        if (!("drainTimeoutSeconds" in $$source)) {
            this["drainTimeoutSeconds"] = 0;
        }
        if (!("protocolVersion" in $$source)) {
            this["protocolVersion"] = "";
        }
        if (!("exposeTools" in $$source)) {
            this["exposeTools"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerSpecDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerSpecDetail {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType0;
        const $$createField14_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cmd" in $$parsedSource) {
            $$parsedSource["cmd"] = $$createField2_0($$parsedSource["cmd"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField3_0($$parsedSource["env"]);
        }
        if ("exposeTools" in $$parsedSource) {
            $$parsedSource["exposeTools"] = $$createField14_0($$parsedSource["exposeTools"]);
        }
        return new ServerSpecDetail($$parsedSource as Partial<ServerSpecDetail>);
    }
}

export class StartCause {
    "reason": string;
    "caller"?: string;
    "toolName"?: string;
    "profile"?: string;
    "policy"?: StartCausePolicy | null;
    "timestamp": string;

    /** Creates a new StartCause instance. */
    constructor($$source: Partial<StartCause> = {}) {
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartCause instance from a string or object.
     */
    static createFrom($$source: any = {}): StartCause {
        const $$createField4_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("policy" in $$parsedSource) {
            $$parsedSource["policy"] = $$createField4_0($$parsedSource["policy"]);
        }
        return new StartCause($$parsedSource as Partial<StartCause>);
    }
}

export class StartCausePolicy {
    "activationMode": string;
    "minReady": number;

    /** Creates a new StartCausePolicy instance. */
    constructor($$source: Partial<StartCausePolicy> = {}) {
        if (!("activationMode" in $$source)) {
            this["activationMode"] = "";
        }
        if (!("minReady" in $$source)) {
            this["minReady"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartCausePolicy instance from a string or object.
     */
    static createFrom($$source: any = {}): StartCausePolicy {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartCausePolicy($$parsedSource as Partial<StartCausePolicy>);
    }
}

/**
 * StartCoreOptions controls how the core is started in Wails.
 */
export class StartCoreOptions {
    "mode"?: string;
    "configPath"?: string;
    "metricsEnabled"?: boolean | null;
    "healthzEnabled"?: boolean | null;

    /** Creates a new StartCoreOptions instance. */
    constructor($$source: Partial<StartCoreOptions> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartCoreOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): StartCoreOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartCoreOptions($$parsedSource as Partial<StartCoreOptions>);
    }
}

/**
 * SubAgentConfigDetail contains the runtime-level SubAgent LLM provider config
 */
export class SubAgentConfigDetail {
    "model": string;
    "provider": string;
    "apiKeyEnvVar": string;
    "baseURL": string;
    "maxToolsPerRequest": number;
    "filterPrompt": string;

    /** Creates a new SubAgentConfigDetail instance. */
    constructor($$source: Partial<SubAgentConfigDetail> = {}) {
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("apiKeyEnvVar" in $$source)) {
            this["apiKeyEnvVar"] = "";
        }
        if (!("baseURL" in $$source)) {
            this["baseURL"] = "";
        }
        if (!("maxToolsPerRequest" in $$source)) {
            this["maxToolsPerRequest"] = 0;
        }
        if (!("filterPrompt" in $$source)) {
            this["filterPrompt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubAgentConfigDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): SubAgentConfigDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SubAgentConfigDetail($$parsedSource as Partial<SubAgentConfigDetail>);
    }
}

/**
 * ToolEntry represents a single tool for the frontend
 */
export class ToolEntry {
    "name": string;
    "toolJson": json$0.RawMessage;
    "specKey": string;
    "serverName": string;

    /** Creates a new ToolEntry instance. */
    constructor($$source: Partial<ToolEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("toolJson" in $$source)) {
            this["toolJson"] = null;
        }
        if (!("specKey" in $$source)) {
            this["specKey"] = "";
        }
        if (!("serverName" in $$source)) {
            this["serverName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolEntry($$parsedSource as Partial<ToolEntry>);
    }
}

/**
 * UpdateCallerMappingRequest updates a caller to profile mapping.
 */
export class UpdateCallerMappingRequest {
    "caller": string;
    "profile": string;

    /** Creates a new UpdateCallerMappingRequest instance. */
    constructor($$source: Partial<UpdateCallerMappingRequest> = {}) {
        if (!("caller" in $$source)) {
            this["caller"] = "";
        }
        if (!("profile" in $$source)) {
            this["profile"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCallerMappingRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateCallerMappingRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateCallerMappingRequest($$parsedSource as Partial<UpdateCallerMappingRequest>);
    }
}

/**
 * UpdateProfileSubAgentRequest updates the per-profile SubAgent enabled state
 */
export class UpdateProfileSubAgentRequest {
    "profile": string;
    "enabled": boolean;

    /** Creates a new UpdateProfileSubAgentRequest instance. */
    constructor($$source: Partial<UpdateProfileSubAgentRequest> = {}) {
        if (!("profile" in $$source)) {
            this["profile"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateProfileSubAgentRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateProfileSubAgentRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateProfileSubAgentRequest($$parsedSource as Partial<UpdateProfileSubAgentRequest>);
    }
}

/**
 * UpdateRuntimeConfigRequest updates runtime.yaml configuration.
 */
export class UpdateRuntimeConfigRequest {
    "routeTimeoutSeconds": number;
    "pingIntervalSeconds": number;
    "toolRefreshSeconds": number;
    "toolRefreshConcurrency": number;
    "callerCheckSeconds": number;
    "callerInactiveSeconds": number;
    "serverInitRetryBaseSeconds": number;
    "serverInitRetryMaxSeconds": number;
    "serverInitMaxRetries": number;
    "bootstrapMode": string;
    "bootstrapConcurrency": number;
    "bootstrapTimeoutSeconds": number;
    "defaultActivationMode": string;
    "exposeTools": boolean;
    "toolNamespaceStrategy": string;

    /** Creates a new UpdateRuntimeConfigRequest instance. */
    constructor($$source: Partial<UpdateRuntimeConfigRequest> = {}) {
        if (!("routeTimeoutSeconds" in $$source)) {
            this["routeTimeoutSeconds"] = 0;
        }
        if (!("pingIntervalSeconds" in $$source)) {
            this["pingIntervalSeconds"] = 0;
        }
        if (!("toolRefreshSeconds" in $$source)) {
            this["toolRefreshSeconds"] = 0;
        }
        if (!("toolRefreshConcurrency" in $$source)) {
            this["toolRefreshConcurrency"] = 0;
        }
        if (!("callerCheckSeconds" in $$source)) {
            this["callerCheckSeconds"] = 0;
        }
        if (!("callerInactiveSeconds" in $$source)) {
            this["callerInactiveSeconds"] = 0;
        }
        if (!("serverInitRetryBaseSeconds" in $$source)) {
            this["serverInitRetryBaseSeconds"] = 0;
        }
        if (!("serverInitRetryMaxSeconds" in $$source)) {
            this["serverInitRetryMaxSeconds"] = 0;
        }
        if (!("serverInitMaxRetries" in $$source)) {
            this["serverInitMaxRetries"] = 0;
        }
        if (!("bootstrapMode" in $$source)) {
            this["bootstrapMode"] = "";
        }
        if (!("bootstrapConcurrency" in $$source)) {
            this["bootstrapConcurrency"] = 0;
        }
        if (!("bootstrapTimeoutSeconds" in $$source)) {
            this["bootstrapTimeoutSeconds"] = 0;
        }
        if (!("defaultActivationMode" in $$source)) {
            this["defaultActivationMode"] = "";
        }
        if (!("exposeTools" in $$source)) {
            this["exposeTools"] = false;
        }
        if (!("toolNamespaceStrategy" in $$source)) {
            this["toolNamespaceStrategy"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateRuntimeConfigRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateRuntimeConfigRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateRuntimeConfigRequest($$parsedSource as Partial<UpdateRuntimeConfigRequest>);
    }
}

/**
 * UpdateServerStateRequest updates the disabled state for a server in a profile.
 */
export class UpdateServerStateRequest {
    "profile": string;
    "server": string;
    "disabled": boolean;

    /** Creates a new UpdateServerStateRequest instance. */
    constructor($$source: Partial<UpdateServerStateRequest> = {}) {
        if (!("profile" in $$source)) {
            this["profile"] = "";
        }
        if (!("server" in $$source)) {
            this["server"] = "";
        }
        if (!("disabled" in $$source)) {
            this["disabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateServerStateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateServerStateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateServerStateRequest($$parsedSource as Partial<UpdateServerStateRequest>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = ImportServerSpec.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = StartCause.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = RuntimeConfigDetail.createFrom;
const $$createType7 = ServerSpecDetail.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = ProfileSubAgentConfigDetail.createFrom;
const $$createType10 = PromptEntry.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = RPCTLSConfigDetail.createFrom;
const $$createType13 = ResourceEntry.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = ObservabilityConfigDetail.createFrom;
const $$createType16 = RPCConfigDetail.createFrom;
const $$createType17 = InstanceStatus.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = PoolStats.createFrom;
const $$createType20 = PoolMetrics.createFrom;
const $$createType21 = StartCausePolicy.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
