// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

/**
 * ConfigModeResponse indicates the configuration mode and path
 */
export class ConfigModeResponse {
    /**
     * "single" (file) or "directory"
     */
    "mode": string;

    /**
     * Configuration path
     */
    "path": string;

    /**
     * Whether the config is writable
     */
    "isWritable": boolean;

    /** Creates a new ConfigModeResponse instance. */
    constructor($$source: Partial<ConfigModeResponse> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isWritable" in $$source)) {
            this["isWritable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigModeResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigModeResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigModeResponse($$parsedSource as Partial<ConfigModeResponse>);
    }
}

/**
 * CoreStateResponse 前端获取 Core 状态的响应
 */
export class CoreStateResponse {
    "state": string;
    "uptime": number;
    "error"?: string;

    /** Creates a new CoreStateResponse instance. */
    constructor($$source: Partial<CoreStateResponse> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("uptime" in $$source)) {
            this["uptime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoreStateResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): CoreStateResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CoreStateResponse($$parsedSource as Partial<CoreStateResponse>);
    }
}

/**
 * InfoResponse 控制面板信息响应
 */
export class InfoResponse {
    "name": string;
    "version": string;
    "build": string;

    /** Creates a new InfoResponse instance. */
    constructor($$source: Partial<InfoResponse> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("build" in $$source)) {
            this["build"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InfoResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): InfoResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InfoResponse($$parsedSource as Partial<InfoResponse>);
    }
}

/**
 * InstanceStatus represents the status of a single server instance
 */
export class InstanceStatus {
    "id": string;
    "state": string;
    "busyCount": number;
    "lastActive": string;

    /** Creates a new InstanceStatus instance. */
    constructor($$source: Partial<InstanceStatus> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("busyCount" in $$source)) {
            this["busyCount"] = 0;
        }
        if (!("lastActive" in $$source)) {
            this["lastActive"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstanceStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): InstanceStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstanceStatus($$parsedSource as Partial<InstanceStatus>);
    }
}

/**
 * Manager coordinates Core lifecycle and all UI services
 */
export class Manager {

    /** Creates a new Manager instance. */
    constructor($$source: Partial<Manager> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manager instance from a string or object.
     */
    static createFrom($$source: any = {}): Manager {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Manager($$parsedSource as Partial<Manager>);
    }
}

/**
 * ObservabilityConfigDetail for frontend
 */
export class ObservabilityConfigDetail {
    "listenAddress": string;

    /** Creates a new ObservabilityConfigDetail instance. */
    constructor($$source: Partial<ObservabilityConfigDetail> = {}) {
        if (!("listenAddress" in $$source)) {
            this["listenAddress"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ObservabilityConfigDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): ObservabilityConfigDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ObservabilityConfigDetail($$parsedSource as Partial<ObservabilityConfigDetail>);
    }
}

/**
 * PoolStats contains aggregated statistics for a server pool
 */
export class PoolStats {
    "total": number;
    "ready": number;
    "busy": number;
    "starting": number;
    "draining": number;
    "failed": number;

    /** Creates a new PoolStats instance. */
    constructor($$source: Partial<PoolStats> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("ready" in $$source)) {
            this["ready"] = 0;
        }
        if (!("busy" in $$source)) {
            this["busy"] = 0;
        }
        if (!("starting" in $$source)) {
            this["starting"] = 0;
        }
        if (!("draining" in $$source)) {
            this["draining"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PoolStats instance from a string or object.
     */
    static createFrom($$source: any = {}): PoolStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PoolStats($$parsedSource as Partial<PoolStats>);
    }
}

/**
 * ProfileDetail contains full profile configuration
 */
export class ProfileDetail {
    "name": string;
    "runtime": RuntimeConfigDetail;
    "servers": ServerSpecDetail[];

    /** Creates a new ProfileDetail instance. */
    constructor($$source: Partial<ProfileDetail> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("runtime" in $$source)) {
            this["runtime"] = (new RuntimeConfigDetail());
        }
        if (!("servers" in $$source)) {
            this["servers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileDetail {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("runtime" in $$parsedSource) {
            $$parsedSource["runtime"] = $$createField1_0($$parsedSource["runtime"]);
        }
        if ("servers" in $$parsedSource) {
            $$parsedSource["servers"] = $$createField2_0($$parsedSource["servers"]);
        }
        return new ProfileDetail($$parsedSource as Partial<ProfileDetail>);
    }
}

/**
 * ProfileSummary provides a brief overview of a profile
 */
export class ProfileSummary {
    "name": string;
    "serverCount": number;
    "isDefault": boolean;

    /** Creates a new ProfileSummary instance. */
    constructor($$source: Partial<ProfileSummary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("serverCount" in $$source)) {
            this["serverCount"] = 0;
        }
        if (!("isDefault" in $$source)) {
            this["isDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileSummary($$parsedSource as Partial<ProfileSummary>);
    }
}

/**
 * PromptEntry represents a single prompt for the frontend
 */
export class PromptEntry {
    "name": string;
    "promptJson": json$0.RawMessage;

    /** Creates a new PromptEntry instance. */
    constructor($$source: Partial<PromptEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("promptJson" in $$source)) {
            this["promptJson"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptEntry($$parsedSource as Partial<PromptEntry>);
    }
}

/**
 * PromptPage represents a paginated list of prompts
 */
export class PromptPage {
    "prompts": PromptEntry[];
    "nextCursor"?: string;

    /** Creates a new PromptPage instance. */
    constructor($$source: Partial<PromptPage> = {}) {
        if (!("prompts" in $$source)) {
            this["prompts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptPage instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptPage {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("prompts" in $$parsedSource) {
            $$parsedSource["prompts"] = $$createField0_0($$parsedSource["prompts"]);
        }
        return new PromptPage($$parsedSource as Partial<PromptPage>);
    }
}

/**
 * RPCConfigDetail for frontend
 */
export class RPCConfigDetail {
    "listenAddress": string;
    "maxRecvMsgSize": number;
    "maxSendMsgSize": number;
    "keepaliveTimeSeconds": number;
    "keepaliveTimeoutSeconds": number;
    "socketMode": string;
    "tls": RPCTLSConfigDetail;

    /** Creates a new RPCConfigDetail instance. */
    constructor($$source: Partial<RPCConfigDetail> = {}) {
        if (!("listenAddress" in $$source)) {
            this["listenAddress"] = "";
        }
        if (!("maxRecvMsgSize" in $$source)) {
            this["maxRecvMsgSize"] = 0;
        }
        if (!("maxSendMsgSize" in $$source)) {
            this["maxSendMsgSize"] = 0;
        }
        if (!("keepaliveTimeSeconds" in $$source)) {
            this["keepaliveTimeSeconds"] = 0;
        }
        if (!("keepaliveTimeoutSeconds" in $$source)) {
            this["keepaliveTimeoutSeconds"] = 0;
        }
        if (!("socketMode" in $$source)) {
            this["socketMode"] = "";
        }
        if (!("tls" in $$source)) {
            this["tls"] = (new RPCTLSConfigDetail());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RPCConfigDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): RPCConfigDetail {
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tls" in $$parsedSource) {
            $$parsedSource["tls"] = $$createField6_0($$parsedSource["tls"]);
        }
        return new RPCConfigDetail($$parsedSource as Partial<RPCConfigDetail>);
    }
}

/**
 * RPCTLSConfigDetail for frontend
 */
export class RPCTLSConfigDetail {
    "enabled": boolean;
    "certFile": string;
    "keyFile": string;
    "caFile": string;
    "clientAuth": boolean;

    /** Creates a new RPCTLSConfigDetail instance. */
    constructor($$source: Partial<RPCTLSConfigDetail> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("certFile" in $$source)) {
            this["certFile"] = "";
        }
        if (!("keyFile" in $$source)) {
            this["keyFile"] = "";
        }
        if (!("caFile" in $$source)) {
            this["caFile"] = "";
        }
        if (!("clientAuth" in $$source)) {
            this["clientAuth"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RPCTLSConfigDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): RPCTLSConfigDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RPCTLSConfigDetail($$parsedSource as Partial<RPCTLSConfigDetail>);
    }
}

/**
 * ResourceEntry represents a single resource for the frontend
 */
export class ResourceEntry {
    "uri": string;
    "resourceJson": json$0.RawMessage;

    /** Creates a new ResourceEntry instance. */
    constructor($$source: Partial<ResourceEntry> = {}) {
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("resourceJson" in $$source)) {
            this["resourceJson"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceEntry($$parsedSource as Partial<ResourceEntry>);
    }
}

/**
 * ResourcePage represents a paginated list of resources
 */
export class ResourcePage {
    "resources": ResourceEntry[];
    "nextCursor"?: string;

    /** Creates a new ResourcePage instance. */
    constructor($$source: Partial<ResourcePage> = {}) {
        if (!("resources" in $$source)) {
            this["resources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourcePage instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourcePage {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resources" in $$parsedSource) {
            $$parsedSource["resources"] = $$createField0_0($$parsedSource["resources"]);
        }
        return new ResourcePage($$parsedSource as Partial<ResourcePage>);
    }
}

/**
 * RuntimeConfigDetail contains runtime configuration for frontend
 */
export class RuntimeConfigDetail {
    "routeTimeoutSeconds": number;
    "pingIntervalSeconds": number;
    "toolRefreshSeconds": number;
    "callerCheckSeconds": number;
    "exposeTools": boolean;
    "toolNamespaceStrategy": string;
    "observability": ObservabilityConfigDetail;
    "rpc": RPCConfigDetail;

    /** Creates a new RuntimeConfigDetail instance. */
    constructor($$source: Partial<RuntimeConfigDetail> = {}) {
        if (!("routeTimeoutSeconds" in $$source)) {
            this["routeTimeoutSeconds"] = 0;
        }
        if (!("pingIntervalSeconds" in $$source)) {
            this["pingIntervalSeconds"] = 0;
        }
        if (!("toolRefreshSeconds" in $$source)) {
            this["toolRefreshSeconds"] = 0;
        }
        if (!("callerCheckSeconds" in $$source)) {
            this["callerCheckSeconds"] = 0;
        }
        if (!("exposeTools" in $$source)) {
            this["exposeTools"] = false;
        }
        if (!("toolNamespaceStrategy" in $$source)) {
            this["toolNamespaceStrategy"] = "";
        }
        if (!("observability" in $$source)) {
            this["observability"] = (new ObservabilityConfigDetail());
        }
        if (!("rpc" in $$source)) {
            this["rpc"] = (new RPCConfigDetail());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeConfigDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): RuntimeConfigDetail {
        const $$createField6_0 = $$createType8;
        const $$createField7_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("observability" in $$parsedSource) {
            $$parsedSource["observability"] = $$createField6_0($$parsedSource["observability"]);
        }
        if ("rpc" in $$parsedSource) {
            $$parsedSource["rpc"] = $$createField7_0($$parsedSource["rpc"]);
        }
        return new RuntimeConfigDetail($$parsedSource as Partial<RuntimeConfigDetail>);
    }
}

/**
 * ServerRuntimeStatus contains the runtime status of a server and its instances
 */
export class ServerRuntimeStatus {
    "serverName": string;
    "instances": InstanceStatus[];
    "stats": PoolStats;

    /** Creates a new ServerRuntimeStatus instance. */
    constructor($$source: Partial<ServerRuntimeStatus> = {}) {
        if (!("serverName" in $$source)) {
            this["serverName"] = "";
        }
        if (!("instances" in $$source)) {
            this["instances"] = [];
        }
        if (!("stats" in $$source)) {
            this["stats"] = (new PoolStats());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerRuntimeStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerRuntimeStatus {
        const $$createField1_0 = $$createType11;
        const $$createField2_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("instances" in $$parsedSource) {
            $$parsedSource["instances"] = $$createField1_0($$parsedSource["instances"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField2_0($$parsedSource["stats"]);
        }
        return new ServerRuntimeStatus($$parsedSource as Partial<ServerRuntimeStatus>);
    }
}

/**
 * ServerSpecDetail contains server specification for frontend
 */
export class ServerSpecDetail {
    "name": string;
    "cmd": string[];
    "env": { [_: string]: string };
    "cwd": string;
    "idleSeconds": number;
    "maxConcurrent": number;
    "sticky": boolean;
    "persistent": boolean;
    "minReady": number;
    "drainTimeoutSeconds": number;
    "protocolVersion": string;
    "exposeTools": string[];

    /** Creates a new ServerSpecDetail instance. */
    constructor($$source: Partial<ServerSpecDetail> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("cmd" in $$source)) {
            this["cmd"] = [];
        }
        if (!("env" in $$source)) {
            this["env"] = {};
        }
        if (!("cwd" in $$source)) {
            this["cwd"] = "";
        }
        if (!("idleSeconds" in $$source)) {
            this["idleSeconds"] = 0;
        }
        if (!("maxConcurrent" in $$source)) {
            this["maxConcurrent"] = 0;
        }
        if (!("sticky" in $$source)) {
            this["sticky"] = false;
        }
        if (!("persistent" in $$source)) {
            this["persistent"] = false;
        }
        if (!("minReady" in $$source)) {
            this["minReady"] = 0;
        }
        if (!("drainTimeoutSeconds" in $$source)) {
            this["drainTimeoutSeconds"] = 0;
        }
        if (!("protocolVersion" in $$source)) {
            this["protocolVersion"] = "";
        }
        if (!("exposeTools" in $$source)) {
            this["exposeTools"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerSpecDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerSpecDetail {
        const $$createField1_0 = $$createType13;
        const $$createField2_0 = $$createType14;
        const $$createField11_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cmd" in $$parsedSource) {
            $$parsedSource["cmd"] = $$createField1_0($$parsedSource["cmd"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField2_0($$parsedSource["env"]);
        }
        if ("exposeTools" in $$parsedSource) {
            $$parsedSource["exposeTools"] = $$createField11_0($$parsedSource["exposeTools"]);
        }
        return new ServerSpecDetail($$parsedSource as Partial<ServerSpecDetail>);
    }
}

/**
 * ToolEntry represents a single tool for the frontend
 */
export class ToolEntry {
    "name": string;
    "toolJson": json$0.RawMessage;

    /** Creates a new ToolEntry instance. */
    constructor($$source: Partial<ToolEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("toolJson" in $$source)) {
            this["toolJson"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolEntry($$parsedSource as Partial<ToolEntry>);
    }
}

// Private type creation functions
const $$createType0 = RuntimeConfigDetail.createFrom;
const $$createType1 = ServerSpecDetail.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = PromptEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = RPCTLSConfigDetail.createFrom;
const $$createType6 = ResourceEntry.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = ObservabilityConfigDetail.createFrom;
const $$createType9 = RPCConfigDetail.createFrom;
const $$createType10 = InstanceStatus.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = PoolStats.createFrom;
const $$createType13 = $Create.Array($Create.Any);
const $$createType14 = $Create.Map($Create.Any, $Create.Any);
