// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

/**
 * CoreStateResponse 前端获取 Core 状态的响应
 */
export class CoreStateResponse {
    "state": string;
    "uptime": number;
    "error"?: string;

    /** Creates a new CoreStateResponse instance. */
    constructor($$source: Partial<CoreStateResponse> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("uptime" in $$source)) {
            this["uptime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoreStateResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): CoreStateResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CoreStateResponse($$parsedSource as Partial<CoreStateResponse>);
    }
}

/**
 * InfoResponse 控制面板信息响应
 */
export class InfoResponse {
    "name": string;
    "version": string;
    "build": string;

    /** Creates a new InfoResponse instance. */
    constructor($$source: Partial<InfoResponse> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("build" in $$source)) {
            this["build"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InfoResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): InfoResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InfoResponse($$parsedSource as Partial<InfoResponse>);
    }
}

/**
 * Manager coordinates Core lifecycle and all UI services
 */
export class Manager {

    /** Creates a new Manager instance. */
    constructor($$source: Partial<Manager> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manager instance from a string or object.
     */
    static createFrom($$source: any = {}): Manager {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Manager($$parsedSource as Partial<Manager>);
    }
}

/**
 * PromptEntry represents a single prompt for the frontend
 */
export class PromptEntry {
    "name": string;
    "promptJson": json$0.RawMessage;

    /** Creates a new PromptEntry instance. */
    constructor($$source: Partial<PromptEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("promptJson" in $$source)) {
            this["promptJson"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptEntry($$parsedSource as Partial<PromptEntry>);
    }
}

/**
 * PromptPage represents a paginated list of prompts
 */
export class PromptPage {
    "prompts": PromptEntry[];
    "nextCursor"?: string;

    /** Creates a new PromptPage instance. */
    constructor($$source: Partial<PromptPage> = {}) {
        if (!("prompts" in $$source)) {
            this["prompts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptPage instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptPage {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("prompts" in $$parsedSource) {
            $$parsedSource["prompts"] = $$createField0_0($$parsedSource["prompts"]);
        }
        return new PromptPage($$parsedSource as Partial<PromptPage>);
    }
}

/**
 * ResourceEntry represents a single resource for the frontend
 */
export class ResourceEntry {
    "uri": string;
    "resourceJson": json$0.RawMessage;

    /** Creates a new ResourceEntry instance. */
    constructor($$source: Partial<ResourceEntry> = {}) {
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("resourceJson" in $$source)) {
            this["resourceJson"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceEntry($$parsedSource as Partial<ResourceEntry>);
    }
}

/**
 * ResourcePage represents a paginated list of resources
 */
export class ResourcePage {
    "resources": ResourceEntry[];
    "nextCursor"?: string;

    /** Creates a new ResourcePage instance. */
    constructor($$source: Partial<ResourcePage> = {}) {
        if (!("resources" in $$source)) {
            this["resources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourcePage instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourcePage {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resources" in $$parsedSource) {
            $$parsedSource["resources"] = $$createField0_0($$parsedSource["resources"]);
        }
        return new ResourcePage($$parsedSource as Partial<ResourcePage>);
    }
}

/**
 * ToolEntry represents a single tool for the frontend
 */
export class ToolEntry {
    "name": string;
    "toolJson": json$0.RawMessage;

    /** Creates a new ToolEntry instance. */
    constructor($$source: Partial<ToolEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("toolJson" in $$source)) {
            this["toolJson"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolEntry($$parsedSource as Partial<ToolEntry>);
    }
}

// Private type creation functions
const $$createType0 = PromptEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ResourceEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
