// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RuntimeService exposes runtime status APIs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetActiveCallers returns active caller registrations.
 */
export function GetActiveCallers(): $CancellablePromise<$models.ActiveCaller[]> {
    return $Call.ByID(831132197).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetRuntimeStatus returns the runtime status of all server pools.
 */
export function GetRuntimeStatus(): $CancellablePromise<$models.ServerRuntimeStatus[]> {
    return $Call.ByID(3809513373).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetServerInitStatus returns per-server initialization status.
 */
export function GetServerInitStatus(): $CancellablePromise<$models.ServerInitStatus[]> {
    return $Call.ByID(2082060570).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * RetryServerInit triggers a manual retry for a suspended server init.
 */
export function RetryServerInit(req: $models.RetryServerInitRequest): $CancellablePromise<void> {
    return $Call.ByID(4137522882, req);
}

// Private type creation functions
const $$createType0 = $models.ActiveCaller.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ServerRuntimeStatus.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.ServerInitStatus.createFrom;
const $$createType5 = $Create.Array($$createType4);
