// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServerService exposes server configuration APIs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteServer removes a server from the config file.
 */
export function DeleteServer(req: $models.DeleteServerRequest): $CancellablePromise<void> {
    return $Call.ByID(556059800, req);
}

/**
 * GetServer returns server detail by name.
 */
export function GetServer(name: string): $CancellablePromise<$models.ServerDetail | null> {
    return $Call.ByID(3422535455, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListServers returns all configured servers.
 */
export function ListServers(): $CancellablePromise<$models.ServerSummary[]> {
    return $Call.ByID(1496030688).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SetServerDisabled updates the disabled state for a server.
 */
export function SetServerDisabled(req: $models.UpdateServerStateRequest): $CancellablePromise<void> {
    return $Call.ByID(4009478283, req);
}

// Private type creation functions
const $$createType0 = $models.ServerSpecDetail.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ServerSummary.createFrom;
const $$createType3 = $Create.Array($$createType2);
