// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SubAgentService exposes SubAgent configuration APIs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetProfileSubAgentConfig returns the per-profile SubAgent enabled state.
 */
export function GetProfileSubAgentConfig(profileName: string): $CancellablePromise<$models.ProfileSubAgentConfigDetail> {
    return $Call.ByID(2051781048, profileName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetSubAgentConfig returns the runtime-level SubAgent configuration.
 */
export function GetSubAgentConfig(): $CancellablePromise<$models.SubAgentConfigDetail> {
    return $Call.ByID(1084533949).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * IsSubAgentAvailable returns whether SubAgent infrastructure is configured.
 */
export function IsSubAgentAvailable(): $CancellablePromise<boolean> {
    return $Call.ByID(2461967930);
}

/**
 * SetProfileSubAgentEnabled updates the per-profile SubAgent enabled state.
 */
export function SetProfileSubAgentEnabled(req: $models.UpdateProfileSubAgentRequest): $CancellablePromise<void> {
    return $Call.ByID(2622835255, req);
}

// Private type creation functions
const $$createType0 = $models.ProfileSubAgentConfigDetail.createFrom;
const $$createType1 = $models.SubAgentConfigDetail.createFrom;
