// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService exposes system-level utility APIs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetVersion returns app version.
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(1530545722);
}

/**
 * HandleURLScheme handles URL Scheme invocations.
 */
export function HandleURLScheme(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(3412451802, rawURL);
}

/**
 * Ping responds with pong.
 */
export function Ping(): $CancellablePromise<string> {
    return $Call.ByID(436844050);
}

/**
 * ResolveMcpdmcpPath resolves the mcpdmcp executable path.
 */
export function ResolveMcpdmcpPath(): $CancellablePromise<string> {
    return $Call.ByID(1439007697);
}
