// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsService 为 Wails 前端提供 Go 服务接口
 * 职责：桥接核心 app 层，不包含业务逻辑
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CallTool 调用指定工具
 */
export function CallTool(name: string, args: json$0.RawMessage, routingKey: string): $CancellablePromise<json$0.RawMessage> {
    return $Call.ByID(721877447, name, args, routingKey);
}

/**
 * GetCoreState 获取 Core 当前状态
 */
export function GetCoreState(): $CancellablePromise<$models.CoreStateResponse> {
    return $Call.ByID(1503257149).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetInfo 获取控制面板信息
 */
export function GetInfo(): $CancellablePromise<$models.InfoResponse> {
    return $Call.ByID(659019143).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetPrompt 获取提示模板内容
 */
export function GetPrompt(name: string, args: json$0.RawMessage): $CancellablePromise<json$0.RawMessage> {
    return $Call.ByID(761557393, name, args);
}

/**
 * GetVersion 获取应用版本信息（示例导出方法）
 * Wails 会自动为导出方法生成 JS 绑定
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(1378407693);
}

/**
 * HandleURLScheme 处理 URL Scheme 唤起
 * 职责：解析 URL 并转发给核心层或触发前端导航
 */
export function HandleURLScheme(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(1041842831, rawURL);
}

/**
 * ListPrompts 列出提示模板
 */
export function ListPrompts(cursor: string): $CancellablePromise<$models.PromptPage | null> {
    return $Call.ByID(2106692208, cursor).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListResources 列出资源
 */
export function ListResources(cursor: string): $CancellablePromise<$models.ResourcePage | null> {
    return $Call.ByID(3909930490, cursor).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListTools 列出所有可用工具
 */
export function ListTools(): $CancellablePromise<$models.ToolEntry[]> {
    return $Call.ByID(1487086052).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * Ping 健康检查接口（示例）
 */
export function Ping(): $CancellablePromise<string> {
    return $Call.ByID(271794645);
}

/**
 * ReadResource 读取资源内容
 */
export function ReadResource(uri: string): $CancellablePromise<json$0.RawMessage> {
    return $Call.ByID(2756274881, uri);
}

/**
 * RestartCore 重启 Core
 */
export function RestartCore(): $CancellablePromise<void> {
    return $Call.ByID(2306439687);
}

/**
 * SetManager 注入 Manager 实例
 */
export function SetManager(manager: $models.Manager | null): $CancellablePromise<void> {
    return $Call.ByID(2434023854, manager);
}

/**
 * SetWailsApp 注入 Wails 应用实例（用于事件发送）
 */
export function SetWailsApp(wails: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(169329738, wails);
}

/**
 * StartCore 启动 Core
 */
export function StartCore(): $CancellablePromise<void> {
    return $Call.ByID(389266072);
}

/**
 * StartLogStream 开始日志流（通过 Wails 事件推送）
 */
export function StartLogStream(minLevel: string): $CancellablePromise<void> {
    return $Call.ByID(4219834107, minLevel);
}

/**
 * StopCore 停止 Core
 */
export function StopCore(): $CancellablePromise<void> {
    return $Call.ByID(3663205050);
}

/**
 * StopLogStream 停止日志流
 */
export function StopLogStream(): $CancellablePromise<void> {
    return $Call.ByID(4194966221);
}

// Private type creation functions
const $$createType0 = $models.CoreStateResponse.createFrom;
const $$createType1 = $models.InfoResponse.createFrom;
const $$createType2 = $models.PromptPage.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.ResourcePage.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.ToolEntry.createFrom;
const $$createType7 = $Create.Array($$createType6);
