// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsService 为 Wails 前端提供 Go 服务接口
 * 职责：桥接核心 app 层，不包含业务逻辑
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CallTool 调用指定工具
 */
export function CallTool(name: string, args: json$0.RawMessage, routingKey: string): $CancellablePromise<json$0.RawMessage> {
    return $Call.ByID(721877447, name, args, routingKey);
}

/**
 * CreateProfile creates a new profile file in the profile store.
 */
export function CreateProfile(req: $models.CreateProfileRequest): $CancellablePromise<void> {
    return $Call.ByID(1320373634, req);
}

/**
 * DeleteProfile deletes a profile file from the profile store.
 */
export function DeleteProfile(req: $models.DeleteProfileRequest): $CancellablePromise<void> {
    return $Call.ByID(1630706107, req);
}

/**
 * DeleteServer removes a server from a profile.
 */
export function DeleteServer(req: $models.DeleteServerRequest): $CancellablePromise<void> {
    return $Call.ByID(1377537969, req);
}

/**
 * GetActiveCallers returns active caller registrations.
 */
export function GetActiveCallers(): $CancellablePromise<$models.ActiveCaller[]> {
    return $Call.ByID(3529704171).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetBootstrapProgress returns the current bootstrap progress
 */
export function GetBootstrapProgress(): $CancellablePromise<$models.BootstrapProgressResponse> {
    return $Call.ByID(175857232).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetCallers 获取 caller 到 profile 的映射
 */
export function GetCallers(): $CancellablePromise<{ [_: string]: string }> {
    return $Call.ByID(1738435433).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetConfigMode returns configuration mode metadata.
 */
export function GetConfigMode(): $CancellablePromise<$models.ConfigModeResponse> {
    return $Call.ByID(2990028974).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetConfigPath 获取配置文件路径
 */
export function GetConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(2220450282);
}

/**
 * GetCoreState 获取 Core 当前状态
 */
export function GetCoreState(): $CancellablePromise<$models.CoreStateResponse> {
    return $Call.ByID(1503257149).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetInfo 获取控制面板信息
 */
export function GetInfo(): $CancellablePromise<$models.InfoResponse> {
    return $Call.ByID(659019143).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetProfile 获取指定 profile 的详细信息
 */
export function GetProfile(name: string): $CancellablePromise<$models.ProfileDetail | null> {
    return $Call.ByID(3878580060, name).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetProfileSubAgentConfig returns the per-profile SubAgent enabled state.
 */
export function GetProfileSubAgentConfig(profileName: string): $CancellablePromise<$models.ProfileSubAgentConfigDetail> {
    return $Call.ByID(1813077673, profileName).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetPrompt 获取提示模板内容
 */
export function GetPrompt(name: string, args: json$0.RawMessage): $CancellablePromise<json$0.RawMessage> {
    return $Call.ByID(761557393, name, args);
}

/**
 * GetRuntimeStatus returns the runtime status of all server pools
 */
export function GetRuntimeStatus(): $CancellablePromise<$models.ServerRuntimeStatus[]> {
    return $Call.ByID(2938457663).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetServerInitStatus returns per-server initialization status
 */
export function GetServerInitStatus(): $CancellablePromise<$models.ServerInitStatus[]> {
    return $Call.ByID(2208834076).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * GetSubAgentConfig returns the runtime-level SubAgent LLM provider configuration.
 */
export function GetSubAgentConfig(): $CancellablePromise<$models.SubAgentConfigDetail> {
    return $Call.ByID(2210812234).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * GetVersion 获取应用版本信息（示例导出方法）
 * Wails 会自动为导出方法生成 JS 绑定
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(1378407693);
}

/**
 * HandleURLScheme 处理 URL Scheme 唤起
 * 职责：解析 URL 并转发给核心层或触发前端导航
 */
export function HandleURLScheme(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(1041842831, rawURL);
}

/**
 * ImportMcpServers writes imported MCP servers into selected profiles.
 */
export function ImportMcpServers(req: $models.ImportMcpServersRequest): $CancellablePromise<void> {
    return $Call.ByID(1586977220, req);
}

/**
 * IsSubAgentAvailable returns whether the SubAgent infrastructure is configured at runtime level.
 */
export function IsSubAgentAvailable(): $CancellablePromise<boolean> {
    return $Call.ByID(543713273);
}

/**
 * ListProfiles 列出所有 profiles
 */
export function ListProfiles(): $CancellablePromise<$models.ProfileSummary[]> {
    return $Call.ByID(3827145375).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * ListPrompts 列出提示模板
 */
export function ListPrompts(cursor: string): $CancellablePromise<$models.PromptPage | null> {
    return $Call.ByID(2106692208, cursor).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * ListResources 列出资源
 */
export function ListResources(cursor: string): $CancellablePromise<$models.ResourcePage | null> {
    return $Call.ByID(3909930490, cursor).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * ListTools 列出所有可用工具
 */
export function ListTools(): $CancellablePromise<$models.ToolEntry[]> {
    return $Call.ByID(1487086052).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * OpenConfigInEditor opens the configuration file/directory in the system default editor
 */
export function OpenConfigInEditor(): $CancellablePromise<void> {
    return $Call.ByID(2866424509);
}

/**
 * Ping 健康检查接口（示例）
 */
export function Ping(): $CancellablePromise<string> {
    return $Call.ByID(271794645);
}

/**
 * ReadResource 读取资源内容
 */
export function ReadResource(uri: string): $CancellablePromise<json$0.RawMessage> {
    return $Call.ByID(2756274881, uri);
}

/**
 * ReloadConfig triggers a configuration reload in the running Core.
 */
export function ReloadConfig(): $CancellablePromise<void> {
    return $Call.ByID(1215728198);
}

/**
 * RemoveCallerMapping removes a caller to profile mapping.
 */
export function RemoveCallerMapping(caller: string): $CancellablePromise<void> {
    return $Call.ByID(766588184, caller);
}

/**
 * ResolveMcpdmcpPath 返回可执行的 mcpdmcp 路径，优先 PATH，其次同目录打包副本，失败时退回命令名
 */
export function ResolveMcpdmcpPath(): $CancellablePromise<string> {
    return $Call.ByID(221290818);
}

/**
 * RestartCore 重启 Core
 */
export function RestartCore(): $CancellablePromise<void> {
    return $Call.ByID(2306439687);
}

/**
 * RetryServerInit triggers a manual retry for a suspended server init.
 */
export function RetryServerInit(req: $models.RetryServerInitRequest): $CancellablePromise<void> {
    return $Call.ByID(675952560, req);
}

/**
 * SetCallerMapping updates a caller to profile mapping.
 */
export function SetCallerMapping(req: $models.UpdateCallerMappingRequest): $CancellablePromise<void> {
    return $Call.ByID(3497067018, req);
}

/**
 * SetManager 注入 Manager 实例
 */
export function SetManager(manager: $models.Manager | null): $CancellablePromise<void> {
    return $Call.ByID(2434023854, manager);
}

/**
 * SetProfileSubAgentEnabled updates the per-profile SubAgent enabled state.
 */
export function SetProfileSubAgentEnabled(req: $models.UpdateProfileSubAgentRequest): $CancellablePromise<void> {
    return $Call.ByID(3888689956, req);
}

/**
 * SetServerDisabled updates the disabled state for a server in a profile.
 */
export function SetServerDisabled(req: $models.UpdateServerStateRequest): $CancellablePromise<void> {
    return $Call.ByID(138235460, req);
}

/**
 * SetWailsApp 注入 Wails 应用实例（用于事件发送）
 */
export function SetWailsApp(wails: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(169329738, wails);
}

/**
 * StartCore 启动 Core
 */
export function StartCore(): $CancellablePromise<void> {
    return $Call.ByID(389266072);
}

/**
 * StartCoreWithOptions starts Core with explicit options.
 */
export function StartCoreWithOptions(opts: $models.StartCoreOptions): $CancellablePromise<void> {
    return $Call.ByID(629304430, opts);
}

/**
 * StartLogStream 开始日志流（通过 Wails 事件推送）
 */
export function StartLogStream(minLevel: string): $CancellablePromise<void> {
    return $Call.ByID(4219834107, minLevel);
}

/**
 * StopCore 停止 Core
 */
export function StopCore(): $CancellablePromise<void> {
    return $Call.ByID(3663205050);
}

/**
 * StopLogStream 停止日志流
 */
export function StopLogStream(): $CancellablePromise<void> {
    return $Call.ByID(4194966221);
}

// Private type creation functions
const $$createType0 = $models.ActiveCaller.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.BootstrapProgressResponse.createFrom;
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $models.ConfigModeResponse.createFrom;
const $$createType5 = $models.CoreStateResponse.createFrom;
const $$createType6 = $models.InfoResponse.createFrom;
const $$createType7 = $models.ProfileDetail.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $models.ProfileSubAgentConfigDetail.createFrom;
const $$createType10 = $models.ServerRuntimeStatus.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.ServerInitStatus.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $models.SubAgentConfigDetail.createFrom;
const $$createType15 = $models.ProfileSummary.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $models.PromptPage.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = $models.ResourcePage.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = $models.ToolEntry.createFrom;
const $$createType22 = $Create.Array($$createType21);
