/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopologyRouteImport } from './routes/topology'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsSubagentRouteImport } from './routes/settings/subagent'
import { Route as SettingsRuntimeRouteImport } from './routes/settings/runtime'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAdvancedRouteImport } from './routes/settings/advanced'

const TopologyRoute = TopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSubagentRoute = SettingsSubagentRouteImport.update({
  id: '/subagent',
  path: '/subagent',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRuntimeRoute = SettingsRuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAdvancedRoute = SettingsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/logs': typeof LogsRoute
  '/plugins': typeof PluginsRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRouteWithChildren
  '/topology': typeof TopologyRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/runtime': typeof SettingsRuntimeRoute
  '/settings/subagent': typeof SettingsSubagentRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/logs': typeof LogsRoute
  '/plugins': typeof PluginsRoute
  '/servers': typeof ServersRoute
  '/topology': typeof TopologyRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/runtime': typeof SettingsRuntimeRoute
  '/settings/subagent': typeof SettingsSubagentRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/logs': typeof LogsRoute
  '/plugins': typeof PluginsRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRouteWithChildren
  '/topology': typeof TopologyRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/runtime': typeof SettingsRuntimeRoute
  '/settings/subagent': typeof SettingsSubagentRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/logs'
    | '/plugins'
    | '/servers'
    | '/settings'
    | '/topology'
    | '/settings/advanced'
    | '/settings/appearance'
    | '/settings/runtime'
    | '/settings/subagent'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/logs'
    | '/plugins'
    | '/servers'
    | '/topology'
    | '/settings/advanced'
    | '/settings/appearance'
    | '/settings/runtime'
    | '/settings/subagent'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/logs'
    | '/plugins'
    | '/servers'
    | '/settings'
    | '/topology'
    | '/settings/advanced'
    | '/settings/appearance'
    | '/settings/runtime'
    | '/settings/subagent'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LogsRoute: typeof LogsRoute
  PluginsRoute: typeof PluginsRoute
  ServersRoute: typeof ServersRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TopologyRoute: typeof TopologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topology': {
      id: '/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof TopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/subagent': {
      id: '/settings/subagent'
      path: '/subagent'
      fullPath: '/settings/subagent'
      preLoaderRoute: typeof SettingsSubagentRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/runtime': {
      id: '/settings/runtime'
      path: '/runtime'
      fullPath: '/settings/runtime'
      preLoaderRoute: typeof SettingsRuntimeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/advanced': {
      id: '/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof SettingsAdvancedRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsAdvancedRoute: typeof SettingsAdvancedRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsRuntimeRoute: typeof SettingsRuntimeRoute
  SettingsSubagentRoute: typeof SettingsSubagentRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAdvancedRoute: SettingsAdvancedRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsRuntimeRoute: SettingsRuntimeRoute,
  SettingsSubagentRoute: SettingsSubagentRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LogsRoute: LogsRoute,
  PluginsRoute: PluginsRoute,
  ServersRoute: ServersRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TopologyRoute: TopologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
