// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService exposes configuration management APIs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfigMode returns configuration mode metadata.
 */
export function GetConfigMode(): $CancellablePromise<$models.ConfigModeResponse> {
    return $Call.ByID(437351141).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetConfigPath returns configuration path.
 */
export function GetConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(502927925);
}

/**
 * GetRuntimeConfig loads runtime configuration from the config file.
 */
export function GetRuntimeConfig(): $CancellablePromise<$models.RuntimeConfigDetail> {
    return $Call.ByID(2805980066).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ImportMcpServers writes imported MCP servers into the config file.
 */
export function ImportMcpServers(req: $models.ImportMcpServersRequest): $CancellablePromise<void> {
    return $Call.ByID(2071061725, req);
}

/**
 * OpenConfigInEditor opens config path in system editor.
 */
export function OpenConfigInEditor(): $CancellablePromise<void> {
    return $Call.ByID(3184354704);
}

/**
 * ReloadConfig triggers a configuration reload in the running Core.
 */
export function ReloadConfig(): $CancellablePromise<void> {
    return $Call.ByID(1537133675);
}

/**
 * UpdateRuntimeConfig writes runtime updates into the config file.
 */
export function UpdateRuntimeConfig(req: $models.UpdateRuntimeConfigRequest): $CancellablePromise<void> {
    return $Call.ByID(3018521129, req);
}

// Private type creation functions
const $$createType0 = types$0.ConfigModeResponse.createFrom;
const $$createType1 = types$0.RuntimeConfigDetail.createFrom;
