// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CoreService exposes core lifecycle APIs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetBootstrapProgress returns bootstrap progress.
 */
export function GetBootstrapProgress(): $CancellablePromise<$models.BootstrapProgressResponse> {
    return $Call.ByID(1772799560).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetCoreState returns current core state.
 */
export function GetCoreState(): $CancellablePromise<$models.CoreStateResponse> {
    return $Call.ByID(891076885).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetInfo returns control plane info.
 */
export function GetInfo(): $CancellablePromise<$models.InfoResponse> {
    return $Call.ByID(4151479887).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * RestartCore restarts the core.
 */
export function RestartCore(): $CancellablePromise<void> {
    return $Call.ByID(691523695);
}

/**
 * StartCore starts the core.
 */
export function StartCore(): $CancellablePromise<void> {
    return $Call.ByID(3641480608);
}

/**
 * StartCoreWithOptions starts the core with explicit options.
 */
export function StartCoreWithOptions(opts: $models.StartCoreOptions): $CancellablePromise<void> {
    return $Call.ByID(282433190, opts);
}

/**
 * StopCore stops the core.
 */
export function StopCore(): $CancellablePromise<void> {
    return $Call.ByID(495027362);
}

// Private type creation functions
const $$createType0 = types$0.BootstrapProgressResponse.createFrom;
const $$createType1 = types$0.CoreStateResponse.createFrom;
const $$createType2 = types$0.InfoResponse.createFrom;
