// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DaemonService exposes system daemon management APIs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function EnsureRunning(req: $models.DaemonEnsureRequest): $CancellablePromise<$models.DaemonStatus> {
    return $Call.ByID(1790177855, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Install(req: $models.DaemonInstallRequest): $CancellablePromise<$models.DaemonStatus> {
    return $Call.ByID(2092811373, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Start(req: $models.DaemonInstallRequest): $CancellablePromise<$models.DaemonStatus> {
    return $Call.ByID(3254438934, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Status(): $CancellablePromise<$models.DaemonStatus> {
    return $Call.ByID(2751504856).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Stop(): $CancellablePromise<$models.DaemonStatus> {
    return $Call.ByID(244979646).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Uninstall(): $CancellablePromise<$models.DaemonStatus> {
    return $Call.ByID(2098394544).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = types$0.DaemonStatus.createFrom;
