// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DebugService exposes debugging utilities.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportDebugSnapshot builds a debug snapshot and returns its JSON payload.
 */
export function ExportDebugSnapshot(): $CancellablePromise<$models.DebugSnapshotResponse> {
    return $Call.ByID(2141628364).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ExportDiagnosticsBundle exports a diagnostics bundle with events, logs, and metrics.
 */
export function ExportDiagnosticsBundle(options: $models.DiagnosticsExportOptions): $CancellablePromise<$models.DiagnosticsBundleResponse> {
    return $Call.ByID(3103041423, options).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = types$0.DebugSnapshotResponse.createFrom;
const $$createType1 = types$0.DiagnosticsBundleResponse.createFrom;
