// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogService streams logs to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * StartLogStream starts log streaming via Wails events.
 */
export function StartLogStream(minLevel: string): $CancellablePromise<void> {
    return $Call.ByID(1041133408, minLevel);
}

/**
 * StopLogStream stops log streaming.
 */
export function StopLogStream(): $CancellablePromise<void> {
    return $Call.ByID(1847913216);
}
