// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * McpTransferService exposes MCP transfer APIs for Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Import reads and imports MCP servers from an external config source.
 */
export function Import(req: $models.McpTransferRequest): $CancellablePromise<$models.McpTransferImportResult> {
    return $Call.ByID(1211521494, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Preview returns importable MCP servers from an external config source.
 */
export function Preview(req: $models.McpTransferRequest): $CancellablePromise<$models.McpTransferPreview> {
    return $Call.ByID(1265180737, req).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = types$0.McpTransferImportResult.createFrom;
const $$createType1 = types$0.McpTransferPreview.createFrom;
