// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

export const ActiveClient = types$0.ActiveClient;
export type ActiveClient = types$0.ActiveClient;

export const BootstrapProgressResponse = types$0.BootstrapProgressResponse;
export type BootstrapProgressResponse = types$0.BootstrapProgressResponse;

export const ConfigModeResponse = types$0.ConfigModeResponse;
export type ConfigModeResponse = types$0.ConfigModeResponse;

export const CoreStateResponse = types$0.CoreStateResponse;
export type CoreStateResponse = types$0.CoreStateResponse;

export const CreateServerRequest = types$0.CreateServerRequest;
export type CreateServerRequest = types$0.CreateServerRequest;

export const DebugSnapshotResponse = types$0.DebugSnapshotResponse;
export type DebugSnapshotResponse = types$0.DebugSnapshotResponse;

export const DeleteServerRequest = types$0.DeleteServerRequest;
export type DeleteServerRequest = types$0.DeleteServerRequest;

export const ImportMcpServersRequest = types$0.ImportMcpServersRequest;
export type ImportMcpServersRequest = types$0.ImportMcpServersRequest;

export const InfoResponse = types$0.InfoResponse;
export type InfoResponse = types$0.InfoResponse;

export const McpTransferImportResult = types$0.McpTransferImportResult;
export type McpTransferImportResult = types$0.McpTransferImportResult;

export const McpTransferPreview = types$0.McpTransferPreview;
export type McpTransferPreview = types$0.McpTransferPreview;

export const McpTransferRequest = types$0.McpTransferRequest;
export type McpTransferRequest = types$0.McpTransferRequest;

export const PluginListEntry = types$0.PluginListEntry;
export type PluginListEntry = types$0.PluginListEntry;

export const PluginMetrics = types$0.PluginMetrics;
export type PluginMetrics = types$0.PluginMetrics;

export const PromptPage = types$0.PromptPage;
export type PromptPage = types$0.PromptPage;

export const ProxyFetchRequest = types$0.ProxyFetchRequest;
export type ProxyFetchRequest = types$0.ProxyFetchRequest;

export const ProxyFetchResponse = types$0.ProxyFetchResponse;
export type ProxyFetchResponse = types$0.ProxyFetchResponse;

export const ResourcePage = types$0.ResourcePage;
export type ResourcePage = types$0.ResourcePage;

export const RetryServerInitRequest = types$0.RetryServerInitRequest;
export type RetryServerInitRequest = types$0.RetryServerInitRequest;

export const RuntimeConfigDetail = types$0.RuntimeConfigDetail;
export type RuntimeConfigDetail = types$0.RuntimeConfigDetail;

export const ServerDetail = types$0.ServerDetail;
export type ServerDetail = types$0.ServerDetail;

export const ServerGroup = types$0.ServerGroup;
export type ServerGroup = types$0.ServerGroup;

export const ServerInitStatus = types$0.ServerInitStatus;
export type ServerInitStatus = types$0.ServerInitStatus;

export const ServerRuntimeStatus = types$0.ServerRuntimeStatus;
export type ServerRuntimeStatus = types$0.ServerRuntimeStatus;

export const ServerSummary = types$0.ServerSummary;
export type ServerSummary = types$0.ServerSummary;

export const StartCoreOptions = types$0.StartCoreOptions;
export type StartCoreOptions = types$0.StartCoreOptions;

export const SubAgentConfigDetail = types$0.SubAgentConfigDetail;
export type SubAgentConfigDetail = types$0.SubAgentConfigDetail;

export const TogglePluginRequest = types$0.TogglePluginRequest;
export type TogglePluginRequest = types$0.TogglePluginRequest;

export const ToolEntry = types$0.ToolEntry;
export type ToolEntry = types$0.ToolEntry;

export const UpdateCheckOptions = types$0.UpdateCheckOptions;
export type UpdateCheckOptions = types$0.UpdateCheckOptions;

export const UpdateCheckResult = types$0.UpdateCheckResult;
export type UpdateCheckResult = types$0.UpdateCheckResult;

export const UpdateRuntimeConfigRequest = types$0.UpdateRuntimeConfigRequest;
export type UpdateRuntimeConfigRequest = types$0.UpdateRuntimeConfigRequest;

export const UpdateServerRequest = types$0.UpdateServerRequest;
export type UpdateServerRequest = types$0.UpdateServerRequest;

export const UpdateServerStateRequest = types$0.UpdateServerStateRequest;
export type UpdateServerStateRequest = types$0.UpdateServerStateRequest;

export const UpdateSubAgentConfigRequest = types$0.UpdateSubAgentConfigRequest;
export type UpdateSubAgentConfigRequest = types$0.UpdateSubAgentConfigRequest;
