// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProxyService forwards HTTP requests for the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Fetch(req: $models.ProxyFetchRequest): $CancellablePromise<$models.ProxyFetchResponse> {
    return $Call.ByID(3161996304, req).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = types$0.ProxyFetchResponse.createFrom;
