// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServerService exposes server configuration APIs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateServer adds a server to the config file.
 */
export function CreateServer(req: $models.CreateServerRequest): $CancellablePromise<void> {
    return $Call.ByID(3772693106, req);
}

/**
 * DeleteServer removes a server from the config file.
 */
export function DeleteServer(req: $models.DeleteServerRequest): $CancellablePromise<void> {
    return $Call.ByID(3058058677, req);
}

/**
 * GetServer returns server detail by name.
 */
export function GetServer(name: string): $CancellablePromise<$models.ServerDetail | null> {
    return $Call.ByID(4289925060, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListServerGroups returns aggregated server groups with tool metadata.
 */
export function ListServerGroups(): $CancellablePromise<$models.ServerGroup[]> {
    return $Call.ByID(3692495062).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListServers returns all configured servers.
 */
export function ListServers(): $CancellablePromise<$models.ServerSummary[]> {
    return $Call.ByID(2333784455).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SetServerDisabled updates the disabled state for a server.
 */
export function SetServerDisabled(req: $models.UpdateServerStateRequest): $CancellablePromise<void> {
    return $Call.ByID(988954880, req);
}

/**
 * UpdateServer updates an existing server in the config file.
 */
export function UpdateServer(req: $models.UpdateServerRequest): $CancellablePromise<void> {
    return $Call.ByID(966239327, req);
}

// Private type creation functions
const $$createType0 = types$0.ServerSpecDetail.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = types$0.ServerGroup.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = types$0.ServerSummary.createFrom;
const $$createType5 = $Create.Array($$createType4);
