// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SubAgentService exposes SubAgent configuration APIs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSubAgentConfig returns the runtime-level SubAgent configuration.
 */
export function GetSubAgentConfig(): $CancellablePromise<$models.SubAgentConfigDetail> {
    return $Call.ByID(1240912298).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * IsSubAgentAvailable returns whether SubAgent infrastructure is configured.
 */
export function IsSubAgentAvailable(): $CancellablePromise<boolean> {
    return $Call.ByID(967016281);
}

/**
 * UpdateSubAgentConfig updates the runtime-level SubAgent config.
 */
export function UpdateSubAgentConfig(req: $models.UpdateSubAgentConfigRequest): $CancellablePromise<void> {
    return $Call.ByID(1393909269, req);
}

// Private type creation functions
const $$createType0 = types$0.SubAgentConfigDetail.createFrom;
