// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService exposes system-level utility APIs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates triggers an immediate update check.
 */
export function CheckForUpdates(): $CancellablePromise<$models.UpdateCheckResult> {
    return $Call.ByID(2091952174).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetUpdateCheckOptions returns current update checker options.
 */
export function GetUpdateCheckOptions(): $CancellablePromise<$models.UpdateCheckOptions> {
    return $Call.ByID(1169463970).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetUpdateDownloadProgress returns current download progress.
 */
export function GetUpdateDownloadProgress(): $CancellablePromise<$models.UpdateDownloadProgress> {
    return $Call.ByID(4162334295).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetUpdateInstallProgress returns current install progress.
 */
export function GetUpdateInstallProgress(): $CancellablePromise<$models.UpdateInstallProgress> {
    return $Call.ByID(1157062288).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetVersion returns app version.
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(4174947991);
}

/**
 * HandleURLScheme handles URL Scheme invocations.
 */
export function HandleURLScheme(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(4264243805, rawURL);
}

/**
 * Ping responds with pong.
 */
export function Ping(): $CancellablePromise<string> {
    return $Call.ByID(1577159839);
}

/**
 * ResolvemcpvmcpPath resolves the mcpvmcp executable path.
 */
export function ResolvemcpvmcpPath(): $CancellablePromise<string> {
    return $Call.ByID(2996998430);
}

/**
 * SetUpdateCheckOptions updates update checker options.
 */
export function SetUpdateCheckOptions(opts: $models.UpdateCheckOptions): $CancellablePromise<$models.UpdateCheckOptions> {
    return $Call.ByID(1723444542, opts).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * StartUpdateDownload starts downloading the latest update asset.
 */
export function StartUpdateDownload(req: $models.UpdateDownloadRequest): $CancellablePromise<$models.UpdateDownloadProgress> {
    return $Call.ByID(2491357336, req).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * StartUpdateInstall starts installing the downloaded update.
 */
export function StartUpdateInstall(req: $models.UpdateInstallRequest): $CancellablePromise<$models.UpdateInstallProgress> {
    return $Call.ByID(2428018587, req).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = types$0.UpdateCheckResult.createFrom;
const $$createType1 = types$0.UpdateCheckOptions.createFrom;
const $$createType2 = types$0.UpdateDownloadProgress.createFrom;
const $$createType3 = types$0.UpdateInstallProgress.createFrom;
