// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UISettingsService exposes UI settings APIs for the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetEffectiveUISettings returns merged UI settings for global + workspace scope.
 */
export function GetEffectiveUISettings(req: $models.UISettingsEffectiveRequest): $CancellablePromise<$models.UISettingsSnapshot> {
    return $Call.ByID(1997592595, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetUISettings returns UI settings for the requested scope.
 */
export function GetUISettings(req: $models.UISettingsScopeRequest): $CancellablePromise<$models.UISettingsSnapshot> {
    return $Call.ByID(1481773436, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetWorkspaceID returns the workspace identifier derived from the config path.
 */
export function GetWorkspaceID(): $CancellablePromise<$models.UISettingsWorkspaceIDResponse> {
    return $Call.ByID(4075576981).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ResetUISettings clears UI settings for the requested scope.
 */
export function ResetUISettings(req: $models.ResetUISettingsRequest): $CancellablePromise<$models.UISettingsSnapshot> {
    return $Call.ByID(1679219475, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateUISettings applies partial updates to UI settings.
 */
export function UpdateUISettings(req: $models.UpdateUISettingsRequest): $CancellablePromise<$models.UISettingsSnapshot> {
    return $Call.ByID(3535072679, req).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = types$0.UISettingsSnapshot.createFrom;
const $$createType1 = types$0.UISettingsWorkspaceIDResponse.createFrom;
