// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: mcpd/control/v1/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_NOTICE      LogLevel = 3
	LogLevel_LOG_LEVEL_WARNING     LogLevel = 4
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 5
	LogLevel_LOG_LEVEL_CRITICAL    LogLevel = 6
	LogLevel_LOG_LEVEL_ALERT       LogLevel = 7
	LogLevel_LOG_LEVEL_EMERGENCY   LogLevel = 8
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_NOTICE",
		4: "LOG_LEVEL_WARNING",
		5: "LOG_LEVEL_ERROR",
		6: "LOG_LEVEL_CRITICAL",
		7: "LOG_LEVEL_ALERT",
		8: "LOG_LEVEL_EMERGENCY",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_NOTICE":      3,
		"LOG_LEVEL_WARNING":     4,
		"LOG_LEVEL_ERROR":       5,
		"LOG_LEVEL_CRITICAL":    6,
		"LOG_LEVEL_ALERT":       7,
		"LOG_LEVEL_EMERGENCY":   8,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_mcpd_control_v1_control_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_mcpd_control_v1_control_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{0}
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Build         string                 `protobuf:"bytes,3,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetInfoResponse) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caller        string                 `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *ListToolsRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *ToolsSnapshot         `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *ListToolsResponse) GetSnapshot() *ToolsSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type WatchToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caller        string                 `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	LastEtag      string                 `protobuf:"bytes,2,opt,name=last_etag,json=lastEtag,proto3" json:"last_etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchToolsRequest) Reset() {
	*x = WatchToolsRequest{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchToolsRequest) ProtoMessage() {}

func (x *WatchToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchToolsRequest.ProtoReflect.Descriptor instead.
func (*WatchToolsRequest) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *WatchToolsRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *WatchToolsRequest) GetLastEtag() string {
	if x != nil {
		return x.LastEtag
	}
	return ""
}

type ToolsSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Etag          string                 `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	Tools         []*ToolDefinition      `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolsSnapshot) Reset() {
	*x = ToolsSnapshot{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolsSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolsSnapshot) ProtoMessage() {}

func (x *ToolsSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolsSnapshot.ProtoReflect.Descriptor instead.
func (*ToolsSnapshot) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *ToolsSnapshot) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *ToolsSnapshot) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ToolDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// JSON encoding of mcp.Tool.
	ToolJson      []byte `protobuf:"bytes,2,opt,name=tool_json,json=toolJson,proto3" json:"tool_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetToolJson() []byte {
	if x != nil {
		return x.ToolJson
	}
	return nil
}

type CallToolRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Caller string                 `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// JSON encoding of tool arguments (mcp.CallToolParams.Arguments).
	ArgumentsJson []byte `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	RoutingKey    string `protobuf:"bytes,4,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolRequest) Reset() {
	*x = CallToolRequest{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolRequest) ProtoMessage() {}

func (x *CallToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolRequest.ProtoReflect.Descriptor instead.
func (*CallToolRequest) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *CallToolRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *CallToolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CallToolRequest) GetArgumentsJson() []byte {
	if x != nil {
		return x.ArgumentsJson
	}
	return nil
}

func (x *CallToolRequest) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

type CallToolResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON encoding of mcp.CallToolResult.
	ResultJson    []byte `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolResponse) Reset() {
	*x = CallToolResponse{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolResponse) ProtoMessage() {}

func (x *CallToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolResponse.ProtoReflect.Descriptor instead.
func (*CallToolResponse) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *CallToolResponse) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

type ListResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caller        string                 `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *ListResourcesRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *ListResourcesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *ResourcesSnapshot     `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *ListResourcesResponse) GetSnapshot() *ResourcesSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *ListResourcesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type WatchResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caller        string                 `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	LastEtag      string                 `protobuf:"bytes,2,opt,name=last_etag,json=lastEtag,proto3" json:"last_etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResourcesRequest) Reset() {
	*x = WatchResourcesRequest{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResourcesRequest) ProtoMessage() {}

func (x *WatchResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResourcesRequest.ProtoReflect.Descriptor instead.
func (*WatchResourcesRequest) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *WatchResourcesRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *WatchResourcesRequest) GetLastEtag() string {
	if x != nil {
		return x.LastEtag
	}
	return ""
}

type ResourcesSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Etag          string                 `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	Resources     []*ResourceDefinition  `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesSnapshot) Reset() {
	*x = ResourcesSnapshot{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesSnapshot) ProtoMessage() {}

func (x *ResourcesSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesSnapshot.ProtoReflect.Descriptor instead.
func (*ResourcesSnapshot) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *ResourcesSnapshot) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *ResourcesSnapshot) GetResources() []*ResourceDefinition {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ResourceDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uri   string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	// JSON encoding of mcp.Resource.
	ResourceJson  []byte `protobuf:"bytes,2,opt,name=resource_json,json=resourceJson,proto3" json:"resource_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceDefinition) Reset() {
	*x = ResourceDefinition{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDefinition) ProtoMessage() {}

func (x *ResourceDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDefinition.ProtoReflect.Descriptor instead.
func (*ResourceDefinition) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *ResourceDefinition) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ResourceDefinition) GetResourceJson() []byte {
	if x != nil {
		return x.ResourceJson
	}
	return nil
}

type ReadResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caller        string                 `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResourceRequest) Reset() {
	*x = ReadResourceRequest{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResourceRequest) ProtoMessage() {}

func (x *ReadResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResourceRequest.ProtoReflect.Descriptor instead.
func (*ReadResourceRequest) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *ReadResourceRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *ReadResourceRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type ReadResourceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON encoding of mcp.ReadResourceResult.
	ResultJson    []byte `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResourceResponse) Reset() {
	*x = ReadResourceResponse{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResourceResponse) ProtoMessage() {}

func (x *ReadResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResourceResponse.ProtoReflect.Descriptor instead.
func (*ReadResourceResponse) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *ReadResourceResponse) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

type ListPromptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caller        string                 `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPromptsRequest) Reset() {
	*x = ListPromptsRequest{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPromptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromptsRequest) ProtoMessage() {}

func (x *ListPromptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromptsRequest.ProtoReflect.Descriptor instead.
func (*ListPromptsRequest) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{16}
}

func (x *ListPromptsRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *ListPromptsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListPromptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *PromptsSnapshot       `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPromptsResponse) Reset() {
	*x = ListPromptsResponse{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPromptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromptsResponse) ProtoMessage() {}

func (x *ListPromptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromptsResponse.ProtoReflect.Descriptor instead.
func (*ListPromptsResponse) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{17}
}

func (x *ListPromptsResponse) GetSnapshot() *PromptsSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *ListPromptsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type WatchPromptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caller        string                 `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	LastEtag      string                 `protobuf:"bytes,2,opt,name=last_etag,json=lastEtag,proto3" json:"last_etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchPromptsRequest) Reset() {
	*x = WatchPromptsRequest{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchPromptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchPromptsRequest) ProtoMessage() {}

func (x *WatchPromptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchPromptsRequest.ProtoReflect.Descriptor instead.
func (*WatchPromptsRequest) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{18}
}

func (x *WatchPromptsRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *WatchPromptsRequest) GetLastEtag() string {
	if x != nil {
		return x.LastEtag
	}
	return ""
}

type PromptsSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Etag          string                 `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	Prompts       []*PromptDefinition    `protobuf:"bytes,2,rep,name=prompts,proto3" json:"prompts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptsSnapshot) Reset() {
	*x = PromptsSnapshot{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptsSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptsSnapshot) ProtoMessage() {}

func (x *PromptsSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptsSnapshot.ProtoReflect.Descriptor instead.
func (*PromptsSnapshot) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{19}
}

func (x *PromptsSnapshot) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *PromptsSnapshot) GetPrompts() []*PromptDefinition {
	if x != nil {
		return x.Prompts
	}
	return nil
}

type PromptDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// JSON encoding of mcp.Prompt.
	PromptJson    []byte `protobuf:"bytes,2,opt,name=prompt_json,json=promptJson,proto3" json:"prompt_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptDefinition) Reset() {
	*x = PromptDefinition{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptDefinition) ProtoMessage() {}

func (x *PromptDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptDefinition.ProtoReflect.Descriptor instead.
func (*PromptDefinition) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{20}
}

func (x *PromptDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PromptDefinition) GetPromptJson() []byte {
	if x != nil {
		return x.PromptJson
	}
	return nil
}

type GetPromptRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Caller string                 `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// JSON encoding of mcp.GetPromptParams.Arguments.
	ArgumentsJson []byte `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromptRequest) Reset() {
	*x = GetPromptRequest{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromptRequest) ProtoMessage() {}

func (x *GetPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromptRequest.ProtoReflect.Descriptor instead.
func (*GetPromptRequest) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{21}
}

func (x *GetPromptRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *GetPromptRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPromptRequest) GetArgumentsJson() []byte {
	if x != nil {
		return x.ArgumentsJson
	}
	return nil
}

type GetPromptResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON encoding of mcp.GetPromptResult.
	ResultJson    []byte `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromptResponse) Reset() {
	*x = GetPromptResponse{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromptResponse) ProtoMessage() {}

func (x *GetPromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromptResponse.ProtoReflect.Descriptor instead.
func (*GetPromptResponse) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{22}
}

func (x *GetPromptResponse) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

type StreamLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caller        string                 `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	MinLevel      LogLevel               `protobuf:"varint,2,opt,name=min_level,json=minLevel,proto3,enum=mcpd.control.v1.LogLevel" json:"min_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{23}
}

func (x *StreamLogsRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *StreamLogsRequest) GetMinLevel() LogLevel {
	if x != nil {
		return x.MinLevel
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

type LogEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Logger            string                 `protobuf:"bytes,1,opt,name=logger,proto3" json:"logger,omitempty"`
	Level             LogLevel               `protobuf:"varint,2,opt,name=level,proto3,enum=mcpd.control.v1.LogLevel" json:"level,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,3,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	// JSON encoding of mcp.LoggingMessageParams.Data.
	DataJson      []byte `protobuf:"bytes,4,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{24}
}

func (x *LogEntry) GetLogger() string {
	if x != nil {
		return x.Logger
	}
	return ""
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogEntry) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *LogEntry) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

var File_mcpd_control_v1_control_proto protoreflect.FileDescriptor

const file_mcpd_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x1dmcpd/control/v1/control.proto\x12\x0fmcpd.control.v1\"\x10\n" +
	"\x0eGetInfoRequest\"U\n" +
	"\x0fGetInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05build\x18\x03 \x01(\tR\x05build\"*\n" +
	"\x10ListToolsRequest\x12\x16\n" +
	"\x06caller\x18\x01 \x01(\tR\x06caller\"O\n" +
	"\x11ListToolsResponse\x12:\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1e.mcpd.control.v1.ToolsSnapshotR\bsnapshot\"H\n" +
	"\x11WatchToolsRequest\x12\x16\n" +
	"\x06caller\x18\x01 \x01(\tR\x06caller\x12\x1b\n" +
	"\tlast_etag\x18\x02 \x01(\tR\blastEtag\"Z\n" +
	"\rToolsSnapshot\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\tR\x04etag\x125\n" +
	"\x05tools\x18\x02 \x03(\v2\x1f.mcpd.control.v1.ToolDefinitionR\x05tools\"A\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\ttool_json\x18\x02 \x01(\fR\btoolJson\"\x85\x01\n" +
	"\x0fCallToolRequest\x12\x16\n" +
	"\x06caller\x18\x01 \x01(\tR\x06caller\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\fR\rargumentsJson\x12\x1f\n" +
	"\vrouting_key\x18\x04 \x01(\tR\n" +
	"routingKey\"3\n" +
	"\x10CallToolResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\fR\n" +
	"resultJson\"F\n" +
	"\x14ListResourcesRequest\x12\x16\n" +
	"\x06caller\x18\x01 \x01(\tR\x06caller\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"x\n" +
	"\x15ListResourcesResponse\x12>\n" +
	"\bsnapshot\x18\x01 \x01(\v2\".mcpd.control.v1.ResourcesSnapshotR\bsnapshot\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"L\n" +
	"\x15WatchResourcesRequest\x12\x16\n" +
	"\x06caller\x18\x01 \x01(\tR\x06caller\x12\x1b\n" +
	"\tlast_etag\x18\x02 \x01(\tR\blastEtag\"j\n" +
	"\x11ResourcesSnapshot\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\tR\x04etag\x12A\n" +
	"\tresources\x18\x02 \x03(\v2#.mcpd.control.v1.ResourceDefinitionR\tresources\"K\n" +
	"\x12ResourceDefinition\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12#\n" +
	"\rresource_json\x18\x02 \x01(\fR\fresourceJson\"?\n" +
	"\x13ReadResourceRequest\x12\x16\n" +
	"\x06caller\x18\x01 \x01(\tR\x06caller\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\"7\n" +
	"\x14ReadResourceResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\fR\n" +
	"resultJson\"D\n" +
	"\x12ListPromptsRequest\x12\x16\n" +
	"\x06caller\x18\x01 \x01(\tR\x06caller\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"t\n" +
	"\x13ListPromptsResponse\x12<\n" +
	"\bsnapshot\x18\x01 \x01(\v2 .mcpd.control.v1.PromptsSnapshotR\bsnapshot\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"J\n" +
	"\x13WatchPromptsRequest\x12\x16\n" +
	"\x06caller\x18\x01 \x01(\tR\x06caller\x12\x1b\n" +
	"\tlast_etag\x18\x02 \x01(\tR\blastEtag\"b\n" +
	"\x0fPromptsSnapshot\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\tR\x04etag\x12;\n" +
	"\aprompts\x18\x02 \x03(\v2!.mcpd.control.v1.PromptDefinitionR\aprompts\"G\n" +
	"\x10PromptDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vprompt_json\x18\x02 \x01(\fR\n" +
	"promptJson\"e\n" +
	"\x10GetPromptRequest\x12\x16\n" +
	"\x06caller\x18\x01 \x01(\tR\x06caller\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\fR\rargumentsJson\"4\n" +
	"\x11GetPromptResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\fR\n" +
	"resultJson\"c\n" +
	"\x11StreamLogsRequest\x12\x16\n" +
	"\x06caller\x18\x01 \x01(\tR\x06caller\x126\n" +
	"\tmin_level\x18\x02 \x01(\x0e2\x19.mcpd.control.v1.LogLevelR\bminLevel\"\xa0\x01\n" +
	"\bLogEntry\x12\x16\n" +
	"\x06logger\x18\x01 \x01(\tR\x06logger\x12/\n" +
	"\x05level\x18\x02 \x01(\x0e2\x19.mcpd.control.v1.LogLevelR\x05level\x12.\n" +
	"\x13timestamp_unix_nano\x18\x03 \x01(\x03R\x11timestampUnixNano\x12\x1b\n" +
	"\tdata_json\x18\x04 \x01(\fR\bdataJson*\xd6\x01\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x14\n" +
	"\x10LOG_LEVEL_NOTICE\x10\x03\x12\x15\n" +
	"\x11LOG_LEVEL_WARNING\x10\x04\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x05\x12\x16\n" +
	"\x12LOG_LEVEL_CRITICAL\x10\x06\x12\x13\n" +
	"\x0fLOG_LEVEL_ALERT\x10\a\x12\x17\n" +
	"\x13LOG_LEVEL_EMERGENCY\x10\b2\xd0\a\n" +
	"\x13ControlPlaneService\x12L\n" +
	"\aGetInfo\x12\x1f.mcpd.control.v1.GetInfoRequest\x1a .mcpd.control.v1.GetInfoResponse\x12R\n" +
	"\tListTools\x12!.mcpd.control.v1.ListToolsRequest\x1a\".mcpd.control.v1.ListToolsResponse\x12R\n" +
	"\n" +
	"WatchTools\x12\".mcpd.control.v1.WatchToolsRequest\x1a\x1e.mcpd.control.v1.ToolsSnapshot0\x01\x12O\n" +
	"\bCallTool\x12 .mcpd.control.v1.CallToolRequest\x1a!.mcpd.control.v1.CallToolResponse\x12^\n" +
	"\rListResources\x12%.mcpd.control.v1.ListResourcesRequest\x1a&.mcpd.control.v1.ListResourcesResponse\x12^\n" +
	"\x0eWatchResources\x12&.mcpd.control.v1.WatchResourcesRequest\x1a\".mcpd.control.v1.ResourcesSnapshot0\x01\x12[\n" +
	"\fReadResource\x12$.mcpd.control.v1.ReadResourceRequest\x1a%.mcpd.control.v1.ReadResourceResponse\x12X\n" +
	"\vListPrompts\x12#.mcpd.control.v1.ListPromptsRequest\x1a$.mcpd.control.v1.ListPromptsResponse\x12X\n" +
	"\fWatchPrompts\x12$.mcpd.control.v1.WatchPromptsRequest\x1a .mcpd.control.v1.PromptsSnapshot0\x01\x12R\n" +
	"\tGetPrompt\x12!.mcpd.control.v1.GetPromptRequest\x1a\".mcpd.control.v1.GetPromptResponse\x12M\n" +
	"\n" +
	"StreamLogs\x12\".mcpd.control.v1.StreamLogsRequest\x1a\x19.mcpd.control.v1.LogEntry0\x01B#Z!mcpd/pkg/api/control/v1;controlv1b\x06proto3"

var (
	file_mcpd_control_v1_control_proto_rawDescOnce sync.Once
	file_mcpd_control_v1_control_proto_rawDescData []byte
)

func file_mcpd_control_v1_control_proto_rawDescGZIP() []byte {
	file_mcpd_control_v1_control_proto_rawDescOnce.Do(func() {
		file_mcpd_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcpd_control_v1_control_proto_rawDesc), len(file_mcpd_control_v1_control_proto_rawDesc)))
	})
	return file_mcpd_control_v1_control_proto_rawDescData
}

var file_mcpd_control_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcpd_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_mcpd_control_v1_control_proto_goTypes = []any{
	(LogLevel)(0),                 // 0: mcpd.control.v1.LogLevel
	(*GetInfoRequest)(nil),        // 1: mcpd.control.v1.GetInfoRequest
	(*GetInfoResponse)(nil),       // 2: mcpd.control.v1.GetInfoResponse
	(*ListToolsRequest)(nil),      // 3: mcpd.control.v1.ListToolsRequest
	(*ListToolsResponse)(nil),     // 4: mcpd.control.v1.ListToolsResponse
	(*WatchToolsRequest)(nil),     // 5: mcpd.control.v1.WatchToolsRequest
	(*ToolsSnapshot)(nil),         // 6: mcpd.control.v1.ToolsSnapshot
	(*ToolDefinition)(nil),        // 7: mcpd.control.v1.ToolDefinition
	(*CallToolRequest)(nil),       // 8: mcpd.control.v1.CallToolRequest
	(*CallToolResponse)(nil),      // 9: mcpd.control.v1.CallToolResponse
	(*ListResourcesRequest)(nil),  // 10: mcpd.control.v1.ListResourcesRequest
	(*ListResourcesResponse)(nil), // 11: mcpd.control.v1.ListResourcesResponse
	(*WatchResourcesRequest)(nil), // 12: mcpd.control.v1.WatchResourcesRequest
	(*ResourcesSnapshot)(nil),     // 13: mcpd.control.v1.ResourcesSnapshot
	(*ResourceDefinition)(nil),    // 14: mcpd.control.v1.ResourceDefinition
	(*ReadResourceRequest)(nil),   // 15: mcpd.control.v1.ReadResourceRequest
	(*ReadResourceResponse)(nil),  // 16: mcpd.control.v1.ReadResourceResponse
	(*ListPromptsRequest)(nil),    // 17: mcpd.control.v1.ListPromptsRequest
	(*ListPromptsResponse)(nil),   // 18: mcpd.control.v1.ListPromptsResponse
	(*WatchPromptsRequest)(nil),   // 19: mcpd.control.v1.WatchPromptsRequest
	(*PromptsSnapshot)(nil),       // 20: mcpd.control.v1.PromptsSnapshot
	(*PromptDefinition)(nil),      // 21: mcpd.control.v1.PromptDefinition
	(*GetPromptRequest)(nil),      // 22: mcpd.control.v1.GetPromptRequest
	(*GetPromptResponse)(nil),     // 23: mcpd.control.v1.GetPromptResponse
	(*StreamLogsRequest)(nil),     // 24: mcpd.control.v1.StreamLogsRequest
	(*LogEntry)(nil),              // 25: mcpd.control.v1.LogEntry
}
var file_mcpd_control_v1_control_proto_depIdxs = []int32{
	6,  // 0: mcpd.control.v1.ListToolsResponse.snapshot:type_name -> mcpd.control.v1.ToolsSnapshot
	7,  // 1: mcpd.control.v1.ToolsSnapshot.tools:type_name -> mcpd.control.v1.ToolDefinition
	13, // 2: mcpd.control.v1.ListResourcesResponse.snapshot:type_name -> mcpd.control.v1.ResourcesSnapshot
	14, // 3: mcpd.control.v1.ResourcesSnapshot.resources:type_name -> mcpd.control.v1.ResourceDefinition
	20, // 4: mcpd.control.v1.ListPromptsResponse.snapshot:type_name -> mcpd.control.v1.PromptsSnapshot
	21, // 5: mcpd.control.v1.PromptsSnapshot.prompts:type_name -> mcpd.control.v1.PromptDefinition
	0,  // 6: mcpd.control.v1.StreamLogsRequest.min_level:type_name -> mcpd.control.v1.LogLevel
	0,  // 7: mcpd.control.v1.LogEntry.level:type_name -> mcpd.control.v1.LogLevel
	1,  // 8: mcpd.control.v1.ControlPlaneService.GetInfo:input_type -> mcpd.control.v1.GetInfoRequest
	3,  // 9: mcpd.control.v1.ControlPlaneService.ListTools:input_type -> mcpd.control.v1.ListToolsRequest
	5,  // 10: mcpd.control.v1.ControlPlaneService.WatchTools:input_type -> mcpd.control.v1.WatchToolsRequest
	8,  // 11: mcpd.control.v1.ControlPlaneService.CallTool:input_type -> mcpd.control.v1.CallToolRequest
	10, // 12: mcpd.control.v1.ControlPlaneService.ListResources:input_type -> mcpd.control.v1.ListResourcesRequest
	12, // 13: mcpd.control.v1.ControlPlaneService.WatchResources:input_type -> mcpd.control.v1.WatchResourcesRequest
	15, // 14: mcpd.control.v1.ControlPlaneService.ReadResource:input_type -> mcpd.control.v1.ReadResourceRequest
	17, // 15: mcpd.control.v1.ControlPlaneService.ListPrompts:input_type -> mcpd.control.v1.ListPromptsRequest
	19, // 16: mcpd.control.v1.ControlPlaneService.WatchPrompts:input_type -> mcpd.control.v1.WatchPromptsRequest
	22, // 17: mcpd.control.v1.ControlPlaneService.GetPrompt:input_type -> mcpd.control.v1.GetPromptRequest
	24, // 18: mcpd.control.v1.ControlPlaneService.StreamLogs:input_type -> mcpd.control.v1.StreamLogsRequest
	2,  // 19: mcpd.control.v1.ControlPlaneService.GetInfo:output_type -> mcpd.control.v1.GetInfoResponse
	4,  // 20: mcpd.control.v1.ControlPlaneService.ListTools:output_type -> mcpd.control.v1.ListToolsResponse
	6,  // 21: mcpd.control.v1.ControlPlaneService.WatchTools:output_type -> mcpd.control.v1.ToolsSnapshot
	9,  // 22: mcpd.control.v1.ControlPlaneService.CallTool:output_type -> mcpd.control.v1.CallToolResponse
	11, // 23: mcpd.control.v1.ControlPlaneService.ListResources:output_type -> mcpd.control.v1.ListResourcesResponse
	13, // 24: mcpd.control.v1.ControlPlaneService.WatchResources:output_type -> mcpd.control.v1.ResourcesSnapshot
	16, // 25: mcpd.control.v1.ControlPlaneService.ReadResource:output_type -> mcpd.control.v1.ReadResourceResponse
	18, // 26: mcpd.control.v1.ControlPlaneService.ListPrompts:output_type -> mcpd.control.v1.ListPromptsResponse
	20, // 27: mcpd.control.v1.ControlPlaneService.WatchPrompts:output_type -> mcpd.control.v1.PromptsSnapshot
	23, // 28: mcpd.control.v1.ControlPlaneService.GetPrompt:output_type -> mcpd.control.v1.GetPromptResponse
	25, // 29: mcpd.control.v1.ControlPlaneService.StreamLogs:output_type -> mcpd.control.v1.LogEntry
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_mcpd_control_v1_control_proto_init() }
func file_mcpd_control_v1_control_proto_init() {
	if File_mcpd_control_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcpd_control_v1_control_proto_rawDesc), len(file_mcpd_control_v1_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcpd_control_v1_control_proto_goTypes,
		DependencyIndexes: file_mcpd_control_v1_control_proto_depIdxs,
		EnumInfos:         file_mcpd_control_v1_control_proto_enumTypes,
		MessageInfos:      file_mcpd_control_v1_control_proto_msgTypes,
	}.Build()
	File_mcpd_control_v1_control_proto = out.File
	file_mcpd_control_v1_control_proto_goTypes = nil
	file_mcpd_control_v1_control_proto_depIdxs = nil
}
