// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: mcpd/control/v1/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_NOTICE      LogLevel = 3
	LogLevel_LOG_LEVEL_WARNING     LogLevel = 4
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 5
	LogLevel_LOG_LEVEL_CRITICAL    LogLevel = 6
	LogLevel_LOG_LEVEL_ALERT       LogLevel = 7
	LogLevel_LOG_LEVEL_EMERGENCY   LogLevel = 8
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_NOTICE",
		4: "LOG_LEVEL_WARNING",
		5: "LOG_LEVEL_ERROR",
		6: "LOG_LEVEL_CRITICAL",
		7: "LOG_LEVEL_ALERT",
		8: "LOG_LEVEL_EMERGENCY",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_NOTICE":      3,
		"LOG_LEVEL_WARNING":     4,
		"LOG_LEVEL_ERROR":       5,
		"LOG_LEVEL_CRITICAL":    6,
		"LOG_LEVEL_ALERT":       7,
		"LOG_LEVEL_EMERGENCY":   8,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_mcpd_control_v1_control_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_mcpd_control_v1_control_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{0}
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Build         string                 `protobuf:"bytes,3,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetInfoResponse) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{2}
}

type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *ToolsSnapshot         `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *ListToolsResponse) GetSnapshot() *ToolsSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type WatchToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastEtag      string                 `protobuf:"bytes,1,opt,name=last_etag,json=lastEtag,proto3" json:"last_etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchToolsRequest) Reset() {
	*x = WatchToolsRequest{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchToolsRequest) ProtoMessage() {}

func (x *WatchToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchToolsRequest.ProtoReflect.Descriptor instead.
func (*WatchToolsRequest) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *WatchToolsRequest) GetLastEtag() string {
	if x != nil {
		return x.LastEtag
	}
	return ""
}

type ToolsSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Etag          string                 `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	Tools         []*ToolDefinition      `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolsSnapshot) Reset() {
	*x = ToolsSnapshot{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolsSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolsSnapshot) ProtoMessage() {}

func (x *ToolsSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolsSnapshot.ProtoReflect.Descriptor instead.
func (*ToolsSnapshot) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *ToolsSnapshot) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *ToolsSnapshot) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ToolDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// JSON encoding of mcp.Tool.
	ToolJson      []byte `protobuf:"bytes,2,opt,name=tool_json,json=toolJson,proto3" json:"tool_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetToolJson() []byte {
	if x != nil {
		return x.ToolJson
	}
	return nil
}

type CallToolRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// JSON encoding of tool arguments (mcp.CallToolParams.Arguments).
	ArgumentsJson []byte `protobuf:"bytes,2,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	RoutingKey    string `protobuf:"bytes,3,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolRequest) Reset() {
	*x = CallToolRequest{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolRequest) ProtoMessage() {}

func (x *CallToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolRequest.ProtoReflect.Descriptor instead.
func (*CallToolRequest) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *CallToolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CallToolRequest) GetArgumentsJson() []byte {
	if x != nil {
		return x.ArgumentsJson
	}
	return nil
}

func (x *CallToolRequest) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

type CallToolResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON encoding of mcp.CallToolResult.
	ResultJson    []byte `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolResponse) Reset() {
	*x = CallToolResponse{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolResponse) ProtoMessage() {}

func (x *CallToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolResponse.ProtoReflect.Descriptor instead.
func (*CallToolResponse) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *CallToolResponse) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

type StreamLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLevel      LogLevel               `protobuf:"varint,1,opt,name=min_level,json=minLevel,proto3,enum=mcpd.control.v1.LogLevel" json:"min_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *StreamLogsRequest) GetMinLevel() LogLevel {
	if x != nil {
		return x.MinLevel
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

type LogEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Logger            string                 `protobuf:"bytes,1,opt,name=logger,proto3" json:"logger,omitempty"`
	Level             LogLevel               `protobuf:"varint,2,opt,name=level,proto3,enum=mcpd.control.v1.LogLevel" json:"level,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,3,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	// JSON encoding of mcp.LoggingMessageParams.Data.
	DataJson      []byte `protobuf:"bytes,4,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_mcpd_control_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_mcpd_control_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_mcpd_control_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *LogEntry) GetLogger() string {
	if x != nil {
		return x.Logger
	}
	return ""
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogEntry) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *LogEntry) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

var File_mcpd_control_v1_control_proto protoreflect.FileDescriptor

const file_mcpd_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x1dmcpd/control/v1/control.proto\x12\x0fmcpd.control.v1\"\x10\n" +
	"\x0eGetInfoRequest\"U\n" +
	"\x0fGetInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05build\x18\x03 \x01(\tR\x05build\"\x12\n" +
	"\x10ListToolsRequest\"O\n" +
	"\x11ListToolsResponse\x12:\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1e.mcpd.control.v1.ToolsSnapshotR\bsnapshot\"0\n" +
	"\x11WatchToolsRequest\x12\x1b\n" +
	"\tlast_etag\x18\x01 \x01(\tR\blastEtag\"Z\n" +
	"\rToolsSnapshot\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\tR\x04etag\x125\n" +
	"\x05tools\x18\x02 \x03(\v2\x1f.mcpd.control.v1.ToolDefinitionR\x05tools\"A\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\ttool_json\x18\x02 \x01(\fR\btoolJson\"m\n" +
	"\x0fCallToolRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x02 \x01(\fR\rargumentsJson\x12\x1f\n" +
	"\vrouting_key\x18\x03 \x01(\tR\n" +
	"routingKey\"3\n" +
	"\x10CallToolResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\fR\n" +
	"resultJson\"K\n" +
	"\x11StreamLogsRequest\x126\n" +
	"\tmin_level\x18\x01 \x01(\x0e2\x19.mcpd.control.v1.LogLevelR\bminLevel\"\xa0\x01\n" +
	"\bLogEntry\x12\x16\n" +
	"\x06logger\x18\x01 \x01(\tR\x06logger\x12/\n" +
	"\x05level\x18\x02 \x01(\x0e2\x19.mcpd.control.v1.LogLevelR\x05level\x12.\n" +
	"\x13timestamp_unix_nano\x18\x03 \x01(\x03R\x11timestampUnixNano\x12\x1b\n" +
	"\tdata_json\x18\x04 \x01(\fR\bdataJson*\xd6\x01\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x14\n" +
	"\x10LOG_LEVEL_NOTICE\x10\x03\x12\x15\n" +
	"\x11LOG_LEVEL_WARNING\x10\x04\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x05\x12\x16\n" +
	"\x12LOG_LEVEL_CRITICAL\x10\x06\x12\x13\n" +
	"\x0fLOG_LEVEL_ALERT\x10\a\x12\x17\n" +
	"\x13LOG_LEVEL_EMERGENCY\x10\b2\xab\x03\n" +
	"\x13ControlPlaneService\x12L\n" +
	"\aGetInfo\x12\x1f.mcpd.control.v1.GetInfoRequest\x1a .mcpd.control.v1.GetInfoResponse\x12R\n" +
	"\tListTools\x12!.mcpd.control.v1.ListToolsRequest\x1a\".mcpd.control.v1.ListToolsResponse\x12R\n" +
	"\n" +
	"WatchTools\x12\".mcpd.control.v1.WatchToolsRequest\x1a\x1e.mcpd.control.v1.ToolsSnapshot0\x01\x12O\n" +
	"\bCallTool\x12 .mcpd.control.v1.CallToolRequest\x1a!.mcpd.control.v1.CallToolResponse\x12M\n" +
	"\n" +
	"StreamLogs\x12\".mcpd.control.v1.StreamLogsRequest\x1a\x19.mcpd.control.v1.LogEntry0\x01B#Z!mcpd/pkg/api/control/v1;controlv1b\x06proto3"

var (
	file_mcpd_control_v1_control_proto_rawDescOnce sync.Once
	file_mcpd_control_v1_control_proto_rawDescData []byte
)

func file_mcpd_control_v1_control_proto_rawDescGZIP() []byte {
	file_mcpd_control_v1_control_proto_rawDescOnce.Do(func() {
		file_mcpd_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcpd_control_v1_control_proto_rawDesc), len(file_mcpd_control_v1_control_proto_rawDesc)))
	})
	return file_mcpd_control_v1_control_proto_rawDescData
}

var file_mcpd_control_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcpd_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_mcpd_control_v1_control_proto_goTypes = []any{
	(LogLevel)(0),             // 0: mcpd.control.v1.LogLevel
	(*GetInfoRequest)(nil),    // 1: mcpd.control.v1.GetInfoRequest
	(*GetInfoResponse)(nil),   // 2: mcpd.control.v1.GetInfoResponse
	(*ListToolsRequest)(nil),  // 3: mcpd.control.v1.ListToolsRequest
	(*ListToolsResponse)(nil), // 4: mcpd.control.v1.ListToolsResponse
	(*WatchToolsRequest)(nil), // 5: mcpd.control.v1.WatchToolsRequest
	(*ToolsSnapshot)(nil),     // 6: mcpd.control.v1.ToolsSnapshot
	(*ToolDefinition)(nil),    // 7: mcpd.control.v1.ToolDefinition
	(*CallToolRequest)(nil),   // 8: mcpd.control.v1.CallToolRequest
	(*CallToolResponse)(nil),  // 9: mcpd.control.v1.CallToolResponse
	(*StreamLogsRequest)(nil), // 10: mcpd.control.v1.StreamLogsRequest
	(*LogEntry)(nil),          // 11: mcpd.control.v1.LogEntry
}
var file_mcpd_control_v1_control_proto_depIdxs = []int32{
	6,  // 0: mcpd.control.v1.ListToolsResponse.snapshot:type_name -> mcpd.control.v1.ToolsSnapshot
	7,  // 1: mcpd.control.v1.ToolsSnapshot.tools:type_name -> mcpd.control.v1.ToolDefinition
	0,  // 2: mcpd.control.v1.StreamLogsRequest.min_level:type_name -> mcpd.control.v1.LogLevel
	0,  // 3: mcpd.control.v1.LogEntry.level:type_name -> mcpd.control.v1.LogLevel
	1,  // 4: mcpd.control.v1.ControlPlaneService.GetInfo:input_type -> mcpd.control.v1.GetInfoRequest
	3,  // 5: mcpd.control.v1.ControlPlaneService.ListTools:input_type -> mcpd.control.v1.ListToolsRequest
	5,  // 6: mcpd.control.v1.ControlPlaneService.WatchTools:input_type -> mcpd.control.v1.WatchToolsRequest
	8,  // 7: mcpd.control.v1.ControlPlaneService.CallTool:input_type -> mcpd.control.v1.CallToolRequest
	10, // 8: mcpd.control.v1.ControlPlaneService.StreamLogs:input_type -> mcpd.control.v1.StreamLogsRequest
	2,  // 9: mcpd.control.v1.ControlPlaneService.GetInfo:output_type -> mcpd.control.v1.GetInfoResponse
	4,  // 10: mcpd.control.v1.ControlPlaneService.ListTools:output_type -> mcpd.control.v1.ListToolsResponse
	6,  // 11: mcpd.control.v1.ControlPlaneService.WatchTools:output_type -> mcpd.control.v1.ToolsSnapshot
	9,  // 12: mcpd.control.v1.ControlPlaneService.CallTool:output_type -> mcpd.control.v1.CallToolResponse
	11, // 13: mcpd.control.v1.ControlPlaneService.StreamLogs:output_type -> mcpd.control.v1.LogEntry
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_mcpd_control_v1_control_proto_init() }
func file_mcpd_control_v1_control_proto_init() {
	if File_mcpd_control_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcpd_control_v1_control_proto_rawDesc), len(file_mcpd_control_v1_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcpd_control_v1_control_proto_goTypes,
		DependencyIndexes: file_mcpd_control_v1_control_proto_depIdxs,
		EnumInfos:         file_mcpd_control_v1_control_proto_enumTypes,
		MessageInfos:      file_mcpd_control_v1_control_proto_msgTypes,
	}.Build()
	File_mcpd_control_v1_control_proto = out.File
	file_mcpd_control_v1_control_proto_goTypes = nil
	file_mcpd_control_v1_control_proto_depIdxs = nil
}
