// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: mcpv/control/v1/control.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlaneService_GetInfo_FullMethodName               = "/mcpv.control.v1.ControlPlaneService/GetInfo"
	ControlPlaneService_GetCatalog_FullMethodName            = "/mcpv.control.v1.ControlPlaneService/GetCatalog"
	ControlPlaneService_GetConfigMode_FullMethodName         = "/mcpv.control.v1.ControlPlaneService/GetConfigMode"
	ControlPlaneService_GetRuntimeConfig_FullMethodName      = "/mcpv.control.v1.ControlPlaneService/GetRuntimeConfig"
	ControlPlaneService_UpdateRuntimeConfig_FullMethodName   = "/mcpv.control.v1.ControlPlaneService/UpdateRuntimeConfig"
	ControlPlaneService_ReloadConfig_FullMethodName          = "/mcpv.control.v1.ControlPlaneService/ReloadConfig"
	ControlPlaneService_CreateServer_FullMethodName          = "/mcpv.control.v1.ControlPlaneService/CreateServer"
	ControlPlaneService_UpdateServer_FullMethodName          = "/mcpv.control.v1.ControlPlaneService/UpdateServer"
	ControlPlaneService_SetServerDisabled_FullMethodName     = "/mcpv.control.v1.ControlPlaneService/SetServerDisabled"
	ControlPlaneService_DeleteServer_FullMethodName          = "/mcpv.control.v1.ControlPlaneService/DeleteServer"
	ControlPlaneService_ImportServers_FullMethodName         = "/mcpv.control.v1.ControlPlaneService/ImportServers"
	ControlPlaneService_GetSubAgentConfig_FullMethodName     = "/mcpv.control.v1.ControlPlaneService/GetSubAgentConfig"
	ControlPlaneService_UpdateSubAgentConfig_FullMethodName  = "/mcpv.control.v1.ControlPlaneService/UpdateSubAgentConfig"
	ControlPlaneService_GetPluginStatus_FullMethodName       = "/mcpv.control.v1.ControlPlaneService/GetPluginStatus"
	ControlPlaneService_CreatePlugin_FullMethodName          = "/mcpv.control.v1.ControlPlaneService/CreatePlugin"
	ControlPlaneService_UpdatePlugin_FullMethodName          = "/mcpv.control.v1.ControlPlaneService/UpdatePlugin"
	ControlPlaneService_DeletePlugin_FullMethodName          = "/mcpv.control.v1.ControlPlaneService/DeletePlugin"
	ControlPlaneService_TogglePlugin_FullMethodName          = "/mcpv.control.v1.ControlPlaneService/TogglePlugin"
	ControlPlaneService_RegisterCaller_FullMethodName        = "/mcpv.control.v1.ControlPlaneService/RegisterCaller"
	ControlPlaneService_UnregisterCaller_FullMethodName      = "/mcpv.control.v1.ControlPlaneService/UnregisterCaller"
	ControlPlaneService_ListActiveClients_FullMethodName     = "/mcpv.control.v1.ControlPlaneService/ListActiveClients"
	ControlPlaneService_WatchActiveClients_FullMethodName    = "/mcpv.control.v1.ControlPlaneService/WatchActiveClients"
	ControlPlaneService_ListTools_FullMethodName             = "/mcpv.control.v1.ControlPlaneService/ListTools"
	ControlPlaneService_WatchTools_FullMethodName            = "/mcpv.control.v1.ControlPlaneService/WatchTools"
	ControlPlaneService_CallTool_FullMethodName              = "/mcpv.control.v1.ControlPlaneService/CallTool"
	ControlPlaneService_CallToolTask_FullMethodName          = "/mcpv.control.v1.ControlPlaneService/CallToolTask"
	ControlPlaneService_TasksGet_FullMethodName              = "/mcpv.control.v1.ControlPlaneService/TasksGet"
	ControlPlaneService_TasksList_FullMethodName             = "/mcpv.control.v1.ControlPlaneService/TasksList"
	ControlPlaneService_TasksResult_FullMethodName           = "/mcpv.control.v1.ControlPlaneService/TasksResult"
	ControlPlaneService_TasksCancel_FullMethodName           = "/mcpv.control.v1.ControlPlaneService/TasksCancel"
	ControlPlaneService_ListResources_FullMethodName         = "/mcpv.control.v1.ControlPlaneService/ListResources"
	ControlPlaneService_WatchResources_FullMethodName        = "/mcpv.control.v1.ControlPlaneService/WatchResources"
	ControlPlaneService_ReadResource_FullMethodName          = "/mcpv.control.v1.ControlPlaneService/ReadResource"
	ControlPlaneService_ListPrompts_FullMethodName           = "/mcpv.control.v1.ControlPlaneService/ListPrompts"
	ControlPlaneService_WatchPrompts_FullMethodName          = "/mcpv.control.v1.ControlPlaneService/WatchPrompts"
	ControlPlaneService_GetPrompt_FullMethodName             = "/mcpv.control.v1.ControlPlaneService/GetPrompt"
	ControlPlaneService_StreamLogs_FullMethodName            = "/mcpv.control.v1.ControlPlaneService/StreamLogs"
	ControlPlaneService_WatchRuntimeStatus_FullMethodName    = "/mcpv.control.v1.ControlPlaneService/WatchRuntimeStatus"
	ControlPlaneService_WatchServerInitStatus_FullMethodName = "/mcpv.control.v1.ControlPlaneService/WatchServerInitStatus"
	ControlPlaneService_AutomaticMCP_FullMethodName          = "/mcpv.control.v1.ControlPlaneService/AutomaticMCP"
	ControlPlaneService_AutomaticEval_FullMethodName         = "/mcpv.control.v1.ControlPlaneService/AutomaticEval"
	ControlPlaneService_IsSubAgentEnabled_FullMethodName     = "/mcpv.control.v1.ControlPlaneService/IsSubAgentEnabled"
)

// ControlPlaneServiceClient is the client API for ControlPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlPlaneServiceClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	GetCatalog(ctx context.Context, in *GetCatalogRequest, opts ...grpc.CallOption) (*GetCatalogResponse, error)
	GetConfigMode(ctx context.Context, in *GetConfigModeRequest, opts ...grpc.CallOption) (*GetConfigModeResponse, error)
	GetRuntimeConfig(ctx context.Context, in *GetRuntimeConfigRequest, opts ...grpc.CallOption) (*GetRuntimeConfigResponse, error)
	UpdateRuntimeConfig(ctx context.Context, in *UpdateRuntimeConfigRequest, opts ...grpc.CallOption) (*UpdateRuntimeConfigResponse, error)
	ReloadConfig(ctx context.Context, in *ReloadConfigRequest, opts ...grpc.CallOption) (*ReloadConfigResponse, error)
	CreateServer(ctx context.Context, in *CreateServerRequest, opts ...grpc.CallOption) (*CreateServerResponse, error)
	UpdateServer(ctx context.Context, in *UpdateServerRequest, opts ...grpc.CallOption) (*UpdateServerResponse, error)
	SetServerDisabled(ctx context.Context, in *SetServerDisabledRequest, opts ...grpc.CallOption) (*SetServerDisabledResponse, error)
	DeleteServer(ctx context.Context, in *DeleteServerRequest, opts ...grpc.CallOption) (*DeleteServerResponse, error)
	ImportServers(ctx context.Context, in *ImportServersRequest, opts ...grpc.CallOption) (*ImportServersResponse, error)
	GetSubAgentConfig(ctx context.Context, in *GetSubAgentConfigRequest, opts ...grpc.CallOption) (*GetSubAgentConfigResponse, error)
	UpdateSubAgentConfig(ctx context.Context, in *UpdateSubAgentConfigRequest, opts ...grpc.CallOption) (*UpdateSubAgentConfigResponse, error)
	GetPluginStatus(ctx context.Context, in *GetPluginStatusRequest, opts ...grpc.CallOption) (*GetPluginStatusResponse, error)
	CreatePlugin(ctx context.Context, in *CreatePluginRequest, opts ...grpc.CallOption) (*CreatePluginResponse, error)
	UpdatePlugin(ctx context.Context, in *UpdatePluginRequest, opts ...grpc.CallOption) (*UpdatePluginResponse, error)
	DeletePlugin(ctx context.Context, in *DeletePluginRequest, opts ...grpc.CallOption) (*DeletePluginResponse, error)
	TogglePlugin(ctx context.Context, in *TogglePluginRequest, opts ...grpc.CallOption) (*TogglePluginResponse, error)
	RegisterCaller(ctx context.Context, in *RegisterCallerRequest, opts ...grpc.CallOption) (*RegisterCallerResponse, error)
	UnregisterCaller(ctx context.Context, in *UnregisterCallerRequest, opts ...grpc.CallOption) (*UnregisterCallerResponse, error)
	ListActiveClients(ctx context.Context, in *ListActiveClientsRequest, opts ...grpc.CallOption) (*ListActiveClientsResponse, error)
	WatchActiveClients(ctx context.Context, in *WatchActiveClientsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActiveClientsSnapshot], error)
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error)
	WatchTools(ctx context.Context, in *WatchToolsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ToolsSnapshot], error)
	CallTool(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallToolResponse, error)
	CallToolTask(ctx context.Context, in *CallToolTaskRequest, opts ...grpc.CallOption) (*CallToolTaskResponse, error)
	TasksGet(ctx context.Context, in *TasksGetRequest, opts ...grpc.CallOption) (*TasksGetResponse, error)
	TasksList(ctx context.Context, in *TasksListRequest, opts ...grpc.CallOption) (*TasksListResponse, error)
	TasksResult(ctx context.Context, in *TasksResultRequest, opts ...grpc.CallOption) (*TasksResultResponse, error)
	TasksCancel(ctx context.Context, in *TasksCancelRequest, opts ...grpc.CallOption) (*TasksCancelResponse, error)
	ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error)
	WatchResources(ctx context.Context, in *WatchResourcesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResourcesSnapshot], error)
	ReadResource(ctx context.Context, in *ReadResourceRequest, opts ...grpc.CallOption) (*ReadResourceResponse, error)
	ListPrompts(ctx context.Context, in *ListPromptsRequest, opts ...grpc.CallOption) (*ListPromptsResponse, error)
	WatchPrompts(ctx context.Context, in *WatchPromptsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PromptsSnapshot], error)
	GetPrompt(ctx context.Context, in *GetPromptRequest, opts ...grpc.CallOption) (*GetPromptResponse, error)
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	WatchRuntimeStatus(ctx context.Context, in *WatchRuntimeStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RuntimeStatusSnapshot], error)
	WatchServerInitStatus(ctx context.Context, in *WatchServerInitStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerInitStatusSnapshot], error)
	// SubAgent automatic tool discovery and execution
	AutomaticMCP(ctx context.Context, in *AutomaticMCPRequest, opts ...grpc.CallOption) (*AutomaticMCPResponse, error)
	AutomaticEval(ctx context.Context, in *AutomaticEvalRequest, opts ...grpc.CallOption) (*AutomaticEvalResponse, error)
	IsSubAgentEnabled(ctx context.Context, in *IsSubAgentEnabledRequest, opts ...grpc.CallOption) (*IsSubAgentEnabledResponse, error)
}

type controlPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneServiceClient(cc grpc.ClientConnInterface) ControlPlaneServiceClient {
	return &controlPlaneServiceClient{cc}
}

func (c *controlPlaneServiceClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) GetCatalog(ctx context.Context, in *GetCatalogRequest, opts ...grpc.CallOption) (*GetCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCatalogResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) GetConfigMode(ctx context.Context, in *GetConfigModeRequest, opts ...grpc.CallOption) (*GetConfigModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigModeResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetConfigMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) GetRuntimeConfig(ctx context.Context, in *GetRuntimeConfigRequest, opts ...grpc.CallOption) (*GetRuntimeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuntimeConfigResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetRuntimeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) UpdateRuntimeConfig(ctx context.Context, in *UpdateRuntimeConfigRequest, opts ...grpc.CallOption) (*UpdateRuntimeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRuntimeConfigResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_UpdateRuntimeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ReloadConfig(ctx context.Context, in *ReloadConfigRequest, opts ...grpc.CallOption) (*ReloadConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadConfigResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ReloadConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) CreateServer(ctx context.Context, in *CreateServerRequest, opts ...grpc.CallOption) (*CreateServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateServerResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_CreateServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) UpdateServer(ctx context.Context, in *UpdateServerRequest, opts ...grpc.CallOption) (*UpdateServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateServerResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_UpdateServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) SetServerDisabled(ctx context.Context, in *SetServerDisabledRequest, opts ...grpc.CallOption) (*SetServerDisabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetServerDisabledResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_SetServerDisabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) DeleteServer(ctx context.Context, in *DeleteServerRequest, opts ...grpc.CallOption) (*DeleteServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteServerResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_DeleteServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ImportServers(ctx context.Context, in *ImportServersRequest, opts ...grpc.CallOption) (*ImportServersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportServersResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ImportServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) GetSubAgentConfig(ctx context.Context, in *GetSubAgentConfigRequest, opts ...grpc.CallOption) (*GetSubAgentConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubAgentConfigResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetSubAgentConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) UpdateSubAgentConfig(ctx context.Context, in *UpdateSubAgentConfigRequest, opts ...grpc.CallOption) (*UpdateSubAgentConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSubAgentConfigResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_UpdateSubAgentConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) GetPluginStatus(ctx context.Context, in *GetPluginStatusRequest, opts ...grpc.CallOption) (*GetPluginStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPluginStatusResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetPluginStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) CreatePlugin(ctx context.Context, in *CreatePluginRequest, opts ...grpc.CallOption) (*CreatePluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePluginResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_CreatePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) UpdatePlugin(ctx context.Context, in *UpdatePluginRequest, opts ...grpc.CallOption) (*UpdatePluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePluginResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_UpdatePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) DeletePlugin(ctx context.Context, in *DeletePluginRequest, opts ...grpc.CallOption) (*DeletePluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePluginResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_DeletePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) TogglePlugin(ctx context.Context, in *TogglePluginRequest, opts ...grpc.CallOption) (*TogglePluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TogglePluginResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_TogglePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) RegisterCaller(ctx context.Context, in *RegisterCallerRequest, opts ...grpc.CallOption) (*RegisterCallerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterCallerResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_RegisterCaller_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) UnregisterCaller(ctx context.Context, in *UnregisterCallerRequest, opts ...grpc.CallOption) (*UnregisterCallerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterCallerResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_UnregisterCaller_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ListActiveClients(ctx context.Context, in *ListActiveClientsRequest, opts ...grpc.CallOption) (*ListActiveClientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActiveClientsResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ListActiveClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) WatchActiveClients(ctx context.Context, in *WatchActiveClientsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActiveClientsSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlaneService_ServiceDesc.Streams[0], ControlPlaneService_WatchActiveClients_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchActiveClientsRequest, ActiveClientsSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_WatchActiveClientsClient = grpc.ServerStreamingClient[ActiveClientsSnapshot]

func (c *controlPlaneServiceClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) WatchTools(ctx context.Context, in *WatchToolsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ToolsSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlaneService_ServiceDesc.Streams[1], ControlPlaneService_WatchTools_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchToolsRequest, ToolsSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_WatchToolsClient = grpc.ServerStreamingClient[ToolsSnapshot]

func (c *controlPlaneServiceClient) CallTool(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallToolResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_CallTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) CallToolTask(ctx context.Context, in *CallToolTaskRequest, opts ...grpc.CallOption) (*CallToolTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallToolTaskResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_CallToolTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) TasksGet(ctx context.Context, in *TasksGetRequest, opts ...grpc.CallOption) (*TasksGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TasksGetResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_TasksGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) TasksList(ctx context.Context, in *TasksListRequest, opts ...grpc.CallOption) (*TasksListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TasksListResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_TasksList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) TasksResult(ctx context.Context, in *TasksResultRequest, opts ...grpc.CallOption) (*TasksResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TasksResultResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_TasksResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) TasksCancel(ctx context.Context, in *TasksCancelRequest, opts ...grpc.CallOption) (*TasksCancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TasksCancelResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_TasksCancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourcesResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ListResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) WatchResources(ctx context.Context, in *WatchResourcesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResourcesSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlaneService_ServiceDesc.Streams[2], ControlPlaneService_WatchResources_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchResourcesRequest, ResourcesSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_WatchResourcesClient = grpc.ServerStreamingClient[ResourcesSnapshot]

func (c *controlPlaneServiceClient) ReadResource(ctx context.Context, in *ReadResourceRequest, opts ...grpc.CallOption) (*ReadResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResourceResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ReadResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ListPrompts(ctx context.Context, in *ListPromptsRequest, opts ...grpc.CallOption) (*ListPromptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPromptsResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ListPrompts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) WatchPrompts(ctx context.Context, in *WatchPromptsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PromptsSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlaneService_ServiceDesc.Streams[3], ControlPlaneService_WatchPrompts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchPromptsRequest, PromptsSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_WatchPromptsClient = grpc.ServerStreamingClient[PromptsSnapshot]

func (c *controlPlaneServiceClient) GetPrompt(ctx context.Context, in *GetPromptRequest, opts ...grpc.CallOption) (*GetPromptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPromptResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlaneService_ServiceDesc.Streams[4], ControlPlaneService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_StreamLogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *controlPlaneServiceClient) WatchRuntimeStatus(ctx context.Context, in *WatchRuntimeStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RuntimeStatusSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlaneService_ServiceDesc.Streams[5], ControlPlaneService_WatchRuntimeStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRuntimeStatusRequest, RuntimeStatusSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_WatchRuntimeStatusClient = grpc.ServerStreamingClient[RuntimeStatusSnapshot]

func (c *controlPlaneServiceClient) WatchServerInitStatus(ctx context.Context, in *WatchServerInitStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerInitStatusSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlaneService_ServiceDesc.Streams[6], ControlPlaneService_WatchServerInitStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchServerInitStatusRequest, ServerInitStatusSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_WatchServerInitStatusClient = grpc.ServerStreamingClient[ServerInitStatusSnapshot]

func (c *controlPlaneServiceClient) AutomaticMCP(ctx context.Context, in *AutomaticMCPRequest, opts ...grpc.CallOption) (*AutomaticMCPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutomaticMCPResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_AutomaticMCP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) AutomaticEval(ctx context.Context, in *AutomaticEvalRequest, opts ...grpc.CallOption) (*AutomaticEvalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutomaticEvalResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_AutomaticEval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) IsSubAgentEnabled(ctx context.Context, in *IsSubAgentEnabledRequest, opts ...grpc.CallOption) (*IsSubAgentEnabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsSubAgentEnabledResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_IsSubAgentEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServiceServer is the server API for ControlPlaneService service.
// All implementations must embed UnimplementedControlPlaneServiceServer
// for forward compatibility.
type ControlPlaneServiceServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	GetCatalog(context.Context, *GetCatalogRequest) (*GetCatalogResponse, error)
	GetConfigMode(context.Context, *GetConfigModeRequest) (*GetConfigModeResponse, error)
	GetRuntimeConfig(context.Context, *GetRuntimeConfigRequest) (*GetRuntimeConfigResponse, error)
	UpdateRuntimeConfig(context.Context, *UpdateRuntimeConfigRequest) (*UpdateRuntimeConfigResponse, error)
	ReloadConfig(context.Context, *ReloadConfigRequest) (*ReloadConfigResponse, error)
	CreateServer(context.Context, *CreateServerRequest) (*CreateServerResponse, error)
	UpdateServer(context.Context, *UpdateServerRequest) (*UpdateServerResponse, error)
	SetServerDisabled(context.Context, *SetServerDisabledRequest) (*SetServerDisabledResponse, error)
	DeleteServer(context.Context, *DeleteServerRequest) (*DeleteServerResponse, error)
	ImportServers(context.Context, *ImportServersRequest) (*ImportServersResponse, error)
	GetSubAgentConfig(context.Context, *GetSubAgentConfigRequest) (*GetSubAgentConfigResponse, error)
	UpdateSubAgentConfig(context.Context, *UpdateSubAgentConfigRequest) (*UpdateSubAgentConfigResponse, error)
	GetPluginStatus(context.Context, *GetPluginStatusRequest) (*GetPluginStatusResponse, error)
	CreatePlugin(context.Context, *CreatePluginRequest) (*CreatePluginResponse, error)
	UpdatePlugin(context.Context, *UpdatePluginRequest) (*UpdatePluginResponse, error)
	DeletePlugin(context.Context, *DeletePluginRequest) (*DeletePluginResponse, error)
	TogglePlugin(context.Context, *TogglePluginRequest) (*TogglePluginResponse, error)
	RegisterCaller(context.Context, *RegisterCallerRequest) (*RegisterCallerResponse, error)
	UnregisterCaller(context.Context, *UnregisterCallerRequest) (*UnregisterCallerResponse, error)
	ListActiveClients(context.Context, *ListActiveClientsRequest) (*ListActiveClientsResponse, error)
	WatchActiveClients(*WatchActiveClientsRequest, grpc.ServerStreamingServer[ActiveClientsSnapshot]) error
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
	WatchTools(*WatchToolsRequest, grpc.ServerStreamingServer[ToolsSnapshot]) error
	CallTool(context.Context, *CallToolRequest) (*CallToolResponse, error)
	CallToolTask(context.Context, *CallToolTaskRequest) (*CallToolTaskResponse, error)
	TasksGet(context.Context, *TasksGetRequest) (*TasksGetResponse, error)
	TasksList(context.Context, *TasksListRequest) (*TasksListResponse, error)
	TasksResult(context.Context, *TasksResultRequest) (*TasksResultResponse, error)
	TasksCancel(context.Context, *TasksCancelRequest) (*TasksCancelResponse, error)
	ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error)
	WatchResources(*WatchResourcesRequest, grpc.ServerStreamingServer[ResourcesSnapshot]) error
	ReadResource(context.Context, *ReadResourceRequest) (*ReadResourceResponse, error)
	ListPrompts(context.Context, *ListPromptsRequest) (*ListPromptsResponse, error)
	WatchPrompts(*WatchPromptsRequest, grpc.ServerStreamingServer[PromptsSnapshot]) error
	GetPrompt(context.Context, *GetPromptRequest) (*GetPromptResponse, error)
	StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	WatchRuntimeStatus(*WatchRuntimeStatusRequest, grpc.ServerStreamingServer[RuntimeStatusSnapshot]) error
	WatchServerInitStatus(*WatchServerInitStatusRequest, grpc.ServerStreamingServer[ServerInitStatusSnapshot]) error
	// SubAgent automatic tool discovery and execution
	AutomaticMCP(context.Context, *AutomaticMCPRequest) (*AutomaticMCPResponse, error)
	AutomaticEval(context.Context, *AutomaticEvalRequest) (*AutomaticEvalResponse, error)
	IsSubAgentEnabled(context.Context, *IsSubAgentEnabledRequest) (*IsSubAgentEnabledResponse, error)
	mustEmbedUnimplementedControlPlaneServiceServer()
}

// UnimplementedControlPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServiceServer struct{}

func (UnimplementedControlPlaneServiceServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetCatalog(context.Context, *GetCatalogRequest) (*GetCatalogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCatalog not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetConfigMode(context.Context, *GetConfigModeRequest) (*GetConfigModeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfigMode not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetRuntimeConfig(context.Context, *GetRuntimeConfigRequest) (*GetRuntimeConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRuntimeConfig not implemented")
}
func (UnimplementedControlPlaneServiceServer) UpdateRuntimeConfig(context.Context, *UpdateRuntimeConfigRequest) (*UpdateRuntimeConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRuntimeConfig not implemented")
}
func (UnimplementedControlPlaneServiceServer) ReloadConfig(context.Context, *ReloadConfigRequest) (*ReloadConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadConfig not implemented")
}
func (UnimplementedControlPlaneServiceServer) CreateServer(context.Context, *CreateServerRequest) (*CreateServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateServer not implemented")
}
func (UnimplementedControlPlaneServiceServer) UpdateServer(context.Context, *UpdateServerRequest) (*UpdateServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateServer not implemented")
}
func (UnimplementedControlPlaneServiceServer) SetServerDisabled(context.Context, *SetServerDisabledRequest) (*SetServerDisabledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetServerDisabled not implemented")
}
func (UnimplementedControlPlaneServiceServer) DeleteServer(context.Context, *DeleteServerRequest) (*DeleteServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteServer not implemented")
}
func (UnimplementedControlPlaneServiceServer) ImportServers(context.Context, *ImportServersRequest) (*ImportServersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportServers not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetSubAgentConfig(context.Context, *GetSubAgentConfigRequest) (*GetSubAgentConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubAgentConfig not implemented")
}
func (UnimplementedControlPlaneServiceServer) UpdateSubAgentConfig(context.Context, *UpdateSubAgentConfigRequest) (*UpdateSubAgentConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubAgentConfig not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetPluginStatus(context.Context, *GetPluginStatusRequest) (*GetPluginStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPluginStatus not implemented")
}
func (UnimplementedControlPlaneServiceServer) CreatePlugin(context.Context, *CreatePluginRequest) (*CreatePluginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlugin not implemented")
}
func (UnimplementedControlPlaneServiceServer) UpdatePlugin(context.Context, *UpdatePluginRequest) (*UpdatePluginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePlugin not implemented")
}
func (UnimplementedControlPlaneServiceServer) DeletePlugin(context.Context, *DeletePluginRequest) (*DeletePluginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePlugin not implemented")
}
func (UnimplementedControlPlaneServiceServer) TogglePlugin(context.Context, *TogglePluginRequest) (*TogglePluginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TogglePlugin not implemented")
}
func (UnimplementedControlPlaneServiceServer) RegisterCaller(context.Context, *RegisterCallerRequest) (*RegisterCallerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterCaller not implemented")
}
func (UnimplementedControlPlaneServiceServer) UnregisterCaller(context.Context, *UnregisterCallerRequest) (*UnregisterCallerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterCaller not implemented")
}
func (UnimplementedControlPlaneServiceServer) ListActiveClients(context.Context, *ListActiveClientsRequest) (*ListActiveClientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActiveClients not implemented")
}
func (UnimplementedControlPlaneServiceServer) WatchActiveClients(*WatchActiveClientsRequest, grpc.ServerStreamingServer[ActiveClientsSnapshot]) error {
	return status.Errorf(codes.Unimplemented, "method WatchActiveClients not implemented")
}
func (UnimplementedControlPlaneServiceServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedControlPlaneServiceServer) WatchTools(*WatchToolsRequest, grpc.ServerStreamingServer[ToolsSnapshot]) error {
	return status.Errorf(codes.Unimplemented, "method WatchTools not implemented")
}
func (UnimplementedControlPlaneServiceServer) CallTool(context.Context, *CallToolRequest) (*CallToolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallTool not implemented")
}
func (UnimplementedControlPlaneServiceServer) CallToolTask(context.Context, *CallToolTaskRequest) (*CallToolTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallToolTask not implemented")
}
func (UnimplementedControlPlaneServiceServer) TasksGet(context.Context, *TasksGetRequest) (*TasksGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TasksGet not implemented")
}
func (UnimplementedControlPlaneServiceServer) TasksList(context.Context, *TasksListRequest) (*TasksListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TasksList not implemented")
}
func (UnimplementedControlPlaneServiceServer) TasksResult(context.Context, *TasksResultRequest) (*TasksResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TasksResult not implemented")
}
func (UnimplementedControlPlaneServiceServer) TasksCancel(context.Context, *TasksCancelRequest) (*TasksCancelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TasksCancel not implemented")
}
func (UnimplementedControlPlaneServiceServer) ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResources not implemented")
}
func (UnimplementedControlPlaneServiceServer) WatchResources(*WatchResourcesRequest, grpc.ServerStreamingServer[ResourcesSnapshot]) error {
	return status.Errorf(codes.Unimplemented, "method WatchResources not implemented")
}
func (UnimplementedControlPlaneServiceServer) ReadResource(context.Context, *ReadResourceRequest) (*ReadResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadResource not implemented")
}
func (UnimplementedControlPlaneServiceServer) ListPrompts(context.Context, *ListPromptsRequest) (*ListPromptsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPrompts not implemented")
}
func (UnimplementedControlPlaneServiceServer) WatchPrompts(*WatchPromptsRequest, grpc.ServerStreamingServer[PromptsSnapshot]) error {
	return status.Errorf(codes.Unimplemented, "method WatchPrompts not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetPrompt(context.Context, *GetPromptRequest) (*GetPromptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrompt not implemented")
}
func (UnimplementedControlPlaneServiceServer) StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedControlPlaneServiceServer) WatchRuntimeStatus(*WatchRuntimeStatusRequest, grpc.ServerStreamingServer[RuntimeStatusSnapshot]) error {
	return status.Errorf(codes.Unimplemented, "method WatchRuntimeStatus not implemented")
}
func (UnimplementedControlPlaneServiceServer) WatchServerInitStatus(*WatchServerInitStatusRequest, grpc.ServerStreamingServer[ServerInitStatusSnapshot]) error {
	return status.Errorf(codes.Unimplemented, "method WatchServerInitStatus not implemented")
}
func (UnimplementedControlPlaneServiceServer) AutomaticMCP(context.Context, *AutomaticMCPRequest) (*AutomaticMCPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AutomaticMCP not implemented")
}
func (UnimplementedControlPlaneServiceServer) AutomaticEval(context.Context, *AutomaticEvalRequest) (*AutomaticEvalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AutomaticEval not implemented")
}
func (UnimplementedControlPlaneServiceServer) IsSubAgentEnabled(context.Context, *IsSubAgentEnabledRequest) (*IsSubAgentEnabledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsSubAgentEnabled not implemented")
}
func (UnimplementedControlPlaneServiceServer) mustEmbedUnimplementedControlPlaneServiceServer() {}
func (UnimplementedControlPlaneServiceServer) testEmbeddedByValue()                             {}

// UnsafeControlPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServiceServer will
// result in compilation errors.
type UnsafeControlPlaneServiceServer interface {
	mustEmbedUnimplementedControlPlaneServiceServer()
}

func RegisterControlPlaneServiceServer(s grpc.ServiceRegistrar, srv ControlPlaneServiceServer) {
	// If the following call pancis, it indicates UnimplementedControlPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlaneService_ServiceDesc, srv)
}

func _ControlPlaneService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_GetCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetCatalog(ctx, req.(*GetCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_GetConfigMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetConfigMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetConfigMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetConfigMode(ctx, req.(*GetConfigModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_GetRuntimeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuntimeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetRuntimeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetRuntimeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetRuntimeConfig(ctx, req.(*GetRuntimeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_UpdateRuntimeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRuntimeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).UpdateRuntimeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_UpdateRuntimeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).UpdateRuntimeConfig(ctx, req.(*UpdateRuntimeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ReloadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ReloadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ReloadConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ReloadConfig(ctx, req.(*ReloadConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_CreateServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).CreateServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_CreateServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).CreateServer(ctx, req.(*CreateServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_UpdateServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).UpdateServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_UpdateServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).UpdateServer(ctx, req.(*UpdateServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_SetServerDisabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetServerDisabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).SetServerDisabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_SetServerDisabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).SetServerDisabled(ctx, req.(*SetServerDisabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_DeleteServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).DeleteServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_DeleteServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).DeleteServer(ctx, req.(*DeleteServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ImportServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ImportServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ImportServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ImportServers(ctx, req.(*ImportServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_GetSubAgentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubAgentConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetSubAgentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetSubAgentConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetSubAgentConfig(ctx, req.(*GetSubAgentConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_UpdateSubAgentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubAgentConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).UpdateSubAgentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_UpdateSubAgentConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).UpdateSubAgentConfig(ctx, req.(*UpdateSubAgentConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_GetPluginStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetPluginStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetPluginStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetPluginStatus(ctx, req.(*GetPluginStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_CreatePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).CreatePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_CreatePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).CreatePlugin(ctx, req.(*CreatePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_UpdatePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).UpdatePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_UpdatePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).UpdatePlugin(ctx, req.(*UpdatePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_DeletePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).DeletePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_DeletePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).DeletePlugin(ctx, req.(*DeletePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_TogglePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TogglePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).TogglePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_TogglePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).TogglePlugin(ctx, req.(*TogglePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_RegisterCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCallerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).RegisterCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_RegisterCaller_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).RegisterCaller(ctx, req.(*RegisterCallerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_UnregisterCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterCallerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).UnregisterCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_UnregisterCaller_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).UnregisterCaller(ctx, req.(*UnregisterCallerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ListActiveClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ListActiveClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ListActiveClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ListActiveClients(ctx, req.(*ListActiveClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_WatchActiveClients_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchActiveClientsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServiceServer).WatchActiveClients(m, &grpc.GenericServerStream[WatchActiveClientsRequest, ActiveClientsSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_WatchActiveClientsServer = grpc.ServerStreamingServer[ActiveClientsSnapshot]

func _ControlPlaneService_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_WatchTools_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchToolsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServiceServer).WatchTools(m, &grpc.GenericServerStream[WatchToolsRequest, ToolsSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_WatchToolsServer = grpc.ServerStreamingServer[ToolsSnapshot]

func _ControlPlaneService_CallTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).CallTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_CallTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).CallTool(ctx, req.(*CallToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_CallToolTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallToolTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).CallToolTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_CallToolTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).CallToolTask(ctx, req.(*CallToolTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_TasksGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TasksGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).TasksGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_TasksGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).TasksGet(ctx, req.(*TasksGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_TasksList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TasksListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).TasksList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_TasksList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).TasksList(ctx, req.(*TasksListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_TasksResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TasksResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).TasksResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_TasksResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).TasksResult(ctx, req.(*TasksResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_TasksCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TasksCancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).TasksCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_TasksCancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).TasksCancel(ctx, req.(*TasksCancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ListResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ListResources(ctx, req.(*ListResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_WatchResources_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchResourcesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServiceServer).WatchResources(m, &grpc.GenericServerStream[WatchResourcesRequest, ResourcesSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_WatchResourcesServer = grpc.ServerStreamingServer[ResourcesSnapshot]

func _ControlPlaneService_ReadResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ReadResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ReadResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ReadResource(ctx, req.(*ReadResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ListPrompts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPromptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ListPrompts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ListPrompts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ListPrompts(ctx, req.(*ListPromptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_WatchPrompts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchPromptsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServiceServer).WatchPrompts(m, &grpc.GenericServerStream[WatchPromptsRequest, PromptsSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_WatchPromptsServer = grpc.ServerStreamingServer[PromptsSnapshot]

func _ControlPlaneService_GetPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetPrompt(ctx, req.(*GetPromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServiceServer).StreamLogs(m, &grpc.GenericServerStream[StreamLogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_StreamLogsServer = grpc.ServerStreamingServer[LogEntry]

func _ControlPlaneService_WatchRuntimeStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRuntimeStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServiceServer).WatchRuntimeStatus(m, &grpc.GenericServerStream[WatchRuntimeStatusRequest, RuntimeStatusSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_WatchRuntimeStatusServer = grpc.ServerStreamingServer[RuntimeStatusSnapshot]

func _ControlPlaneService_WatchServerInitStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchServerInitStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServiceServer).WatchServerInitStatus(m, &grpc.GenericServerStream[WatchServerInitStatusRequest, ServerInitStatusSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_WatchServerInitStatusServer = grpc.ServerStreamingServer[ServerInitStatusSnapshot]

func _ControlPlaneService_AutomaticMCP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutomaticMCPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).AutomaticMCP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_AutomaticMCP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).AutomaticMCP(ctx, req.(*AutomaticMCPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_AutomaticEval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutomaticEvalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).AutomaticEval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_AutomaticEval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).AutomaticEval(ctx, req.(*AutomaticEvalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_IsSubAgentEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsSubAgentEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).IsSubAgentEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_IsSubAgentEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).IsSubAgentEnabled(ctx, req.(*IsSubAgentEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlaneService_ServiceDesc is the grpc.ServiceDesc for ControlPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcpv.control.v1.ControlPlaneService",
	HandlerType: (*ControlPlaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _ControlPlaneService_GetInfo_Handler,
		},
		{
			MethodName: "GetCatalog",
			Handler:    _ControlPlaneService_GetCatalog_Handler,
		},
		{
			MethodName: "GetConfigMode",
			Handler:    _ControlPlaneService_GetConfigMode_Handler,
		},
		{
			MethodName: "GetRuntimeConfig",
			Handler:    _ControlPlaneService_GetRuntimeConfig_Handler,
		},
		{
			MethodName: "UpdateRuntimeConfig",
			Handler:    _ControlPlaneService_UpdateRuntimeConfig_Handler,
		},
		{
			MethodName: "ReloadConfig",
			Handler:    _ControlPlaneService_ReloadConfig_Handler,
		},
		{
			MethodName: "CreateServer",
			Handler:    _ControlPlaneService_CreateServer_Handler,
		},
		{
			MethodName: "UpdateServer",
			Handler:    _ControlPlaneService_UpdateServer_Handler,
		},
		{
			MethodName: "SetServerDisabled",
			Handler:    _ControlPlaneService_SetServerDisabled_Handler,
		},
		{
			MethodName: "DeleteServer",
			Handler:    _ControlPlaneService_DeleteServer_Handler,
		},
		{
			MethodName: "ImportServers",
			Handler:    _ControlPlaneService_ImportServers_Handler,
		},
		{
			MethodName: "GetSubAgentConfig",
			Handler:    _ControlPlaneService_GetSubAgentConfig_Handler,
		},
		{
			MethodName: "UpdateSubAgentConfig",
			Handler:    _ControlPlaneService_UpdateSubAgentConfig_Handler,
		},
		{
			MethodName: "GetPluginStatus",
			Handler:    _ControlPlaneService_GetPluginStatus_Handler,
		},
		{
			MethodName: "CreatePlugin",
			Handler:    _ControlPlaneService_CreatePlugin_Handler,
		},
		{
			MethodName: "UpdatePlugin",
			Handler:    _ControlPlaneService_UpdatePlugin_Handler,
		},
		{
			MethodName: "DeletePlugin",
			Handler:    _ControlPlaneService_DeletePlugin_Handler,
		},
		{
			MethodName: "TogglePlugin",
			Handler:    _ControlPlaneService_TogglePlugin_Handler,
		},
		{
			MethodName: "RegisterCaller",
			Handler:    _ControlPlaneService_RegisterCaller_Handler,
		},
		{
			MethodName: "UnregisterCaller",
			Handler:    _ControlPlaneService_UnregisterCaller_Handler,
		},
		{
			MethodName: "ListActiveClients",
			Handler:    _ControlPlaneService_ListActiveClients_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _ControlPlaneService_ListTools_Handler,
		},
		{
			MethodName: "CallTool",
			Handler:    _ControlPlaneService_CallTool_Handler,
		},
		{
			MethodName: "CallToolTask",
			Handler:    _ControlPlaneService_CallToolTask_Handler,
		},
		{
			MethodName: "TasksGet",
			Handler:    _ControlPlaneService_TasksGet_Handler,
		},
		{
			MethodName: "TasksList",
			Handler:    _ControlPlaneService_TasksList_Handler,
		},
		{
			MethodName: "TasksResult",
			Handler:    _ControlPlaneService_TasksResult_Handler,
		},
		{
			MethodName: "TasksCancel",
			Handler:    _ControlPlaneService_TasksCancel_Handler,
		},
		{
			MethodName: "ListResources",
			Handler:    _ControlPlaneService_ListResources_Handler,
		},
		{
			MethodName: "ReadResource",
			Handler:    _ControlPlaneService_ReadResource_Handler,
		},
		{
			MethodName: "ListPrompts",
			Handler:    _ControlPlaneService_ListPrompts_Handler,
		},
		{
			MethodName: "GetPrompt",
			Handler:    _ControlPlaneService_GetPrompt_Handler,
		},
		{
			MethodName: "AutomaticMCP",
			Handler:    _ControlPlaneService_AutomaticMCP_Handler,
		},
		{
			MethodName: "AutomaticEval",
			Handler:    _ControlPlaneService_AutomaticEval_Handler,
		},
		{
			MethodName: "IsSubAgentEnabled",
			Handler:    _ControlPlaneService_IsSubAgentEnabled_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchActiveClients",
			Handler:       _ControlPlaneService_WatchActiveClients_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchTools",
			Handler:       _ControlPlaneService_WatchTools_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchResources",
			Handler:       _ControlPlaneService_WatchResources_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchPrompts",
			Handler:       _ControlPlaneService_WatchPrompts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _ControlPlaneService_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchRuntimeStatus",
			Handler:       _ControlPlaneService_WatchRuntimeStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchServerInitStatus",
			Handler:       _ControlPlaneService_WatchServerInitStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mcpv/control/v1/control.proto",
}
